galaxyproject/galaxy-hub

src/GalaxyUpdates/2015_09/index.md
src/GalaxyUpdates/2015_10/index.md
src/GalaxyUpdates/2015_11/index.md
src/GalaxyUpdates/2015_12/index.md
src/GalaxyUpdates/2016_01/index.md
src/GalaxyUpdates/2016_02/index.md
src/GalaxyUpdates/2016_03/index.md
src/GalaxyUpdates/2016_04/index.md
src/GalaxyUpdates/2016_05/index.md
src/GalaxyUpdates/2016_06/index.md
src/GalaxyUpdates/2016_07/index.md
src/GalaxyUpdates/2016_08/index.md
src/GalaxyUpdates/2016_09/index.md
src/GalaxyUpdates/2016_10/index.md
src/events/Archive/index.md
src/events/index.md

These are all straightforward replacements, and result in a better looking Events page.
Working on this in preparation for publishing December news.  And none of these changes take advantage of any metalsmithery.  Just trying to get through the week here.

Replace events-centric INCLUDEs with actual text of include

---

src/config/menu.yaml

Hi,
I fixed some broken links in the top menu.
Btw, I have a question. Is it normal that some subdirectories start with a lower case letter and other with a upper case letter? 
Bérénice

Fix some links into the top menu

---

build.coffee

It's faster, in any event, though there are still broken links due to, I think, wonky scoping

Link manipulation logic tweaks. - Work in Progress

---

build.coffee
package.json

Adds metalsmith-timer to each step of the build. This can probably be
refactored for DRY, but works for now. Pass the `cache` option to
layouts which gets passed to pug. The layouts plugin does not compile
templates, this allows pug to cache the compiled version itself. For me
the pug stage of the build goes from 70s to <1s.
Autotoc is now the slowest stage at 15s. Much more usable this way.

Add timing to build, cache layouts.

---

src/Admin/GetGalaxy/index.md

It's small, but I ran into this while running through the docs for the very first time.

Update dev git clone url to point to the correct URL.

---

src/Admin/Config/Performance/ProductionServer/index.md

http://sqlalchemy.readthedocs.org/en/rel_0_5/dbengine.html
and
http://www.sqlalchemy.org/docs/05/dbengine.html#dbengine_establishing
are missing.

fix missing link

---

src/news/galaxyis-hiring/index.md

Brought in current links for the job openings page.

Updated links from Emory to JHU (job openings page).

---

src/proteomics/index.md

- Updated link to proteomics ToolShed
- Fixed link to presentation slides
- Removed useless "..."
TO-DO: Link to Andromeda (http://galaxy.nbic.nl/) is broken. Can't find correct link.

Fixed links in proteomics page

---

src/teach/best-practices/index.md

- Fixed grammar issues
- Reorganized best practices to separate training "content" from "techniques"
- Modified sentence structures to make everything uniform and more readable
- Added link to making users admins (for pre-loading data)
TO-DO: Decide on and fill out workshop- and course-specific best practices sections

Best practices page update

---

layouts/layout.pug

'highlight: true' in frontmatter to engage.  If it seems like folks like it, we can make it the default (or opt-out).  It did make some preformatted blocks look weird, to me, though.

Basic opt-in highlighting. 

---

src/tutorials/collections/index.md

Numbered figures for future reference.
Changed wording in few sections. 
Are the 'filter from file', relabel from file', and 'concatenate' tools for collections moving to Main (soon)?
In figure 12, why are there three seemingly redundant 'Auto-assign' buttons?
In figure 16, wouldn't the called peaks be merged (and not the mapped reads)?
Not fixed: 
- references to icons in figures 4a, 6d, 14,

Improve collections tutorial

---

partials/Admin/Config/Performance/LinkBox.html
src/admin/config/apache-external-user-auth/index.md
src/admin/config/apache-proxy/index.md
src/admin/config/external-user-auth/index.md
src/admin/config/index.md
src/admin/config/nginx-external-user-auth/index.md
src/admin/config/nginx-proxy/index.md
src/admin/config/windows/index.md
src/develop/index.md

Also synchronizes some of the nginx / apache docs. Also documents the /api exception needed for CLI clients (thanks @bwlang for the config example)
This also (accidentally) includes the same change as #265 and #267 since neither of those were merged yet and I hadn't seen them.

Various cleanups of admin documentation

---

src/admin/config/apache-proxy/index.md

With Galaxy 17.05, encoded slashes are used for all toolshed tool URLs and thus, without the `AllowEncodedSlashes NoDecode` setting, Apache proxy will be unable to serve Galaxy instances. Also added a note that this setting is not available in the versions of Apache distributed with CentOS 6.

Make AllowEncodedSlashes a requirement

---

src/teach/gtn/index.md

Replaced the **Training Resources Directory** link to http://galaxyproject.github.io/training-material/, the rendered "beautiful" repository for the training materials. I think this is the default link that should be pointed to as people on this hub page are likely trying to find the link to the actual training materials. Also added a sentence pointing to the training material GitHub page as separate link.

Updated link to rendered GTN repository

---

src/admin/config/performance/cluster/index.md

These old links no longer work, and need updating.

Update python-drmaa and slurm-drmaa references

---

src/admin/config/performance/production-server/index.md

The  original [SQLAlchemy documentation URL](http://sqlalchemy.readthedocs.io/en/latest/core/engines.html) is missing. I guess it need be change to  http://docs.sqlalchemy.org/en/latest/core/engines.html.

Update index.md for SQLAlchemy documentation URL

---

src/admin/config/performance/production-server/index.md

I have added some modifications, but please have a closer look as I only tested it on 1 server (Ubuntu 16.04) so far. The python virtualenv from the wget is from 2011 and was causing major issues on our server. Using the virtualenv from pip seems to have worked so far. Further testing in progress.

virtualenv is not working anymore

---

build.js
package.json
src/css/styles.less

I have no experience with metalsmith so feel free to completely redo this. 
This is related to the comment on linking to particular sections on the hub - this should make that easier.

Add links/icon to all headers for permanent linking using metalsmith-headings-identifier

---

src/css/styles.less

fix headingsidentifier icon misplacement on Firefox

---

src/admin/config/index.md

in the admin/config page as indicated by @hrhotz #221

Put AD/LDAP auth link in the production section..

---

src/admin/tools/data-managers/data-manager-xml-syntax/index.md

Backslash escaping isn't rendering properly. Use `` instead.

Escape XML Tags in Headers

---

src/tutorials/g101/index.md

The old link was interpreted as relative and so pointed to a page which didn't exist.

Fix a link to CyVerse in documentation

---

src/learn/datatypes/index.md

The documentation for the `interval` datatype refers to `COMMON` as one of the columns; the correct name for this column is actually `COMMENT`.

Fix typo in documentation for 'interval' datatype

---

src/admin/get-galaxy/index.md

Otherwise if the release branch doesn't exist the checkout fails with:
```
$ git checkout bla
error: pathspec 'bla' did not match any file(s) known to git.
```

Add git fetch to updating galaxy instruction

---

src/develop/api/index.md

blend4j repository has been added to the galaxyproject GitHub project.

Update blend4j links

---

layouts/events_index.pug

I've added some code to render out events in JSON-LD format according to the schema.org/Event specification. 
There are two additional fields in there called _contact_ and _eventType_. These fields aren't recognized by schema.org - but they are currently being proposed as new properties by the Bioschemas group to schema.org (See: [their recommendations to schema.org](http://bioschemas.org/specifications/Event/specification/)
[Here is a tool to test the JSON-LD formatting](https://search.google.com/structured-data/testing-tool)

Render events information in (bio)schema(s).org JSON-LD format

---

layouts/events_index.pug

Duration format must start with P for __period__.
See Duration ISO Standard https://en.wikipedia.org/wiki/ISO_8601#Durations

Fixed mistake in duration format

---

src/admin/tools/data-managers/data-manager-xml-syntax/index.md

The `<source>`, `<target>` and `<value_translation>` tags allow for the use of Cheetah templates. This PR adds text to clarify how they are used.

Clarify use of templates with relevant tags

---

src/events/gcc2019/index.md

from http://www.bioinf.uni-freiburg.de/Galaxy/index.html to https://galaxyproject.eu/freiburg
and the link https://usegalaxy.eu/freiburg was broken, exchanged by https://galaxyproject.eu/freiburg

link to Freiburg Galaxy Team changed

---

partials/Events/GCC2019/Header.html
src/events/gcc2019/abstracts/index.md
src/events/gcc2019/registration/index.md
src/news/2019-03-gcc2019/index.md

Registration for GCC2019 is open. This adds a bigger button to the page.
@tnabtaf feel free to merge whenever you think we are ready.

[WIP] gcc2019 registration is open

---

src/admin/reference-data-repo/index.md

I'd resisted creating a [CVMFS Config Repository](https://cvmfs.readthedocs.io/en/stable/cpt-configure.html#the-config-repository) in the past because you still have to install a client config. But as I've added additional repos, configuring each one has become tedious. People accessing the data repo may also be interested in the singularity, usegalaxy, etc. repos, using the config repo sets all of them up at once.
xref: galaxyproject/ansible-cvmfs#14

Update the CVMFS page to prefer the cvmfs-config repo

---

src/cloud/k8s/gke/index.md

Main changes:
-Separating Helm installation from helm initialization
-Updating to latest working Helm version on GKE, and specifying the used working versions
-Adding information about cluster context (and the fact that this can be run from any shell with the proper context not necessarily from within GKE Cloud Shell)
-Removing manual `kubectl` commands to reset `helm`
-Adding information about how to make sure a previous `helm` installation is not already present before installing a new one (to avoid the problem of confusing two different installations)

Fixing GKE Helm installation tutorial

---

src/use/usegalaxy-be/index.md

Some adaptations to the usegalaxy-be page for the hub. While training is installed, we did not yet test it, so I prefer to add it publicly later

updating usegalaxy-be initial content

---

src/authnz/config/oidc/idps/okta/index.md
src/authnz/config/oidc/idps/okta/login-with-okta.png
src/authnz/config/oidc/idps/okta/register-a-new-app-1.png
src/authnz/config/oidc/index.md
src/authnz/use/oidc/idps/okta/01.png
src/authnz/use/oidc/idps/okta/02.png
src/authnz/use/oidc/idps/okta/index.md
src/authnz/use/oidc/index.md

This is to add documentation for https://github.com/galaxyproject/galaxy/pull/7497. It adds documentation on how to set up Okta as IdP for Galaxy.

Add documentation for Okta OIDC

---

.gitattributes
src/community/devroundtable/devroundtable001.mp4
src/community/devroundtable/index.md

@tnabtaf Look good as a start?
(URL would be  `galaxyproject.org/community/devroundtable/`)
We'll probably want to collect slide links and make this a little more automatic in the future, but I'm not building a new automated index page right now :)

Devroundtable page to collect presentations with links, etc.

---

layouts/events.pug
layouts/events_index.pug
layouts/events_index_webinars.pug
src/events/2020-09-niaid/index.md
src/events/2020-11-du-novo/index.md
src/events/2020-12-chloroplast/index.md

Two things:
* now displaying tease with each event in events listing pages.
* added links to events. Displaying those in events listing pages too.
I'm not sure if updating the NIAID event page like this PR did is a best practice or not.  The du novo event page links outside the hub, so it seems like a good idea to list the video link on the events list (and it isn't listed at the external page).  However, the NIAID page is internal to the hub, and this info was already displayed in a better way on that page.  I dunno.

Displaying tease and (new) links on events listing pages.

---

src/events/2017-10-04-gvl-intro/index.md

`truees` isn't a valid bool, it appears.

Fix invalid boolean value in 2017-10-04-gvl-intro.

---

.github/workflows/optimize-images.yml

Hi!
We have just [tested this action](https://github.com/usegalaxy-eu/website/pull/662) on the EU website and seems to work quite well, see the result [here](https://github.com/usegalaxy-eu/website/pull/663).
I've made this PR in case you want to use it too :)
The first time it runs will probably create a PR with lots of updated images, and then it will only update when there are new images that can be optimized as part of a PR or periodically every Sunday at 11 PM.
Hope it helps!

Add Github Action to optimize all images automatically

---

src/templates/VueArticle.vue
src/utils.js

This works around https://github.com/remarkjs/remark-html/releases/tag/13.0.2 changing the default sanitization in a patch release.
It additionally cuts out redundant parsing that we discovered when this broke.

Fix remark being overly picky about slot parsing

---

gridsome.server.js

The new file should match the old one, with the only exception being the addition of an `id` attribute for each platform.

Re-implement `/use/feed.json` from old Hub

---

content/events/2021-09-papercuts/index.md
gridsome.server.js

Mentioned in the commit message, but we really need to track down what's mangling this stuff in a non-standard way.  Either & should just work, or &amp; should work, but currently an extra \ gets injected somewhere in markdown handling causing the links to break.
Also ran formatting.

Fix time links papercuts

---

src/pages/Index.vue

If `jumbotron.md` is present but empty, it would create a big, blank space on the homepage under the title.
This fixes that.

Omit empty jumbotron.

---

src/index.html
src/layouts/Default.vue
src/main.js

The problem was that sidecar would actually load before the mounted()
function that sets up the configuration was available, causing the
error.  This ensures a consistent order and less prone to error anyway.

Fix gitter sidecar.

---

src/pages/Index.vue

Remove `row` class.
\- Avoid special rules by default.
\- Can add it in the `jumbotron.md` itself if desired.  
Change spacing to rem (@dannon's suggestion in #805), simplify logic a little.

More Jumbotron layout tweaks.

---

src/components/NavBar.vue
src/pages/404.vue
src/pages/Blog.vue
src/pages/Careers.vue
src/pages/Events.vue
src/pages/Index.vue
src/pages/News.vue
src/pages/Search.vue
src/pages/Use.vue
src/pages/events/Archive.vue
src/pages/events/Cofests.vue
src/pages/events/Webinars.vue
src/pages/events/cofests/Papercuts.vue
src/templates/Article.vue
src/templates/Platform.vue
src/templates/VueArticle.vue

A less radical change than #810.
This provides a specific Github url for every current Collection (`Article`, `VueArticle`, `Platform`), and leaves dynamic (`.vue`) pages alone.
It accommodates the different naming of the main `$page` object by basically duck typing: it looks for anything with a `.fileInfo.path` property.
It also doesn't assume anything lacking that is a dynamic page, so for those cases it provides a general link to the repo.

A more conservative improvement to the editUrl NavBar link.

---

src/utils.js

This adds a `decodeURI()` call to handle urls with spaces (represented internally as `%20`) when redirecting from the 404 page.
With this, all types of urls identified in #760 are handled.

404 page: Handle redirecting urls with spaces.

---

src/build/mdfixer.mjs
src/build/run.mjs

Preserve exit codes from subprocesses that die.
Kill the gridsome server if the watcher (for the hot reloader) dies.
Note: this still doesn't return a proper exit code if the watcher dies. That seems to be an issue inherent to using the `unified-args` package.

Build process: Handle unusual exits from child processes in `run.mjs`.

---

src/build/run.mjs
src/components/ArticleHeader.vue
src/utils.js

The `redirect` metadata key triggers the "this page has moved to" message and a redirect after 5 seconds.
But the user could hit the back button or leave via a link in those 5 seconds. Previously, the `setTimeout` would still fire the redirect even if they were already on another page.

Cancel metadata redirect if user has left the page.

---

package.json
src/build/fix-links.mjs
src/build/html-img-to-md.mjs
src/build/keep-newline-before-html.mjs
src/build/mdfixer.mjs
src/build/partition-content.mjs
src/build/preprocess.mjs
src/build/run.mjs
src/pages/Use.vue
src/paths.js
src/utils.js
yarn.lock

As mentioned in #838, `unified-args` was causing problems in the build system. Also, `mdfixer.mjs` contained a lot of ugly workarounds for its peculiarities. A lot of this was because `unified-args` was being used in ways it wasn't intended.
This replaces it with `unified-engine`, which is what `unified-args` uses under the hood. It greatly simplifies the code.
This branch also includes some cleanups of style issues left in the build code.

Replace `unified-args` with `unified-engine` in `mdfixer.mjs`, clean up some build code.

---

src/components/ArticleTableEvents.vue
src/pages/Events.vue
src/pages/events/Archive.vue
src/pages/events/Cofests.vue
src/pages/events/Webinars.vue
src/pages/events/cofests/Papercuts.vue

Another feature from the old Hub: show links like slides, video, etc. in the tease of event listings on pages like `/events/` or `/events/webinars/`.
Also, shrink tease text size.

Show `links` metadata in event listings.

---

.github/workflows/lint.yml
.github/workflows/main.yml

This will cut down on excess CI runs and will only run checks against PRs.

Only run checks on PR, not push

---

.github/workflows/links.yml

It worked, so I can back this off.  It can be manually triggered, or it will run nightly at 11:30.
Once we get the report looking good, we can expand coverage to more frequented pages.

Convert link checking to run nightly at 11:30

---

content/tutorials/nt_rnaseq/index.md

The autogenerated link was causing a strange DOM issue.
- A copy of the <a> element was being added just before the original.
- Caused issues with testing.

Fix issue with first collapsible element in /tutorials/nt-rnaseq/.

---

src/components/ArticleHeader.vue
src/pages/404.vue
src/utils.js

Make the redirect from the 404 page like a normal redirect from a content page: show an alert to the user, then wait 5 seconds.

Pause before redirecting from 404 and explain in an alert.

---

package.json

`package.json` was missing `remark-stringify`, which is used directly in `mdfixer.mjs`.

Make previously implicit dependency remark-stringify explicit.

---

src/build/fix-links.mjs

Adding some checks to prevent `getDirPath()` from failing (with a confusing error message).

fix-links.mjs: Check for necessary values before invoking `getDirPath()`.

---

src/pages/Use.vue

When you're looking at the Platform Directory and you click a link to a Galaxy server, it should probably open in a new tab.

Open links from /use/ to Galaxy servers in new tabs.

---

src/pages/events/Archive.vue

Oops, used the wrong value!
Fixes #893.

Fix mistake in `/events/archive/`: Filter for events older than 1 year, not 0 years.

---

.github/workflows/links-external.yml
.github/workflows/links-internal.yml
.github/workflows/lint.yml
.github/workflows/main.yml
.github/workflows/optimize-images.yml
.github/workflows/publish.yml

Jenkins is being retired; this will swap building/publishing to a github action that will replace it.  Also has the added benefit of providing more visibility to the build/publish infra, and can eventually be used to build and serve PR previews, both good things.

Build and publish action -- migrating from Jenkins

---

content/events/gcc2012/ask-the-organizers.md
content/events/gcc2012/askthe-organizers/index.md
content/events/gcc2012/page-header/index.md

Just noticed some obvious errors in the slots/Inserts for the pages in /events/gcc2012/.

GCC2012: Delete duplicate Insert Markdown files, fix syntax in another.

---

src/build/mdfixer.mjs
src/build/unescape-links.mjs
src/build/unescape-links.test.mjs

`unescape-links.mjs` was mistakenly transforming any link where the text was identical to the url into an autolink, resulting in links like `[/admin/get-galaxy/](/admin/get-galaxy/)` getting turned into `</admin/get-galaxy/>`, which doesn't work.
This should fix that by using rules from the CommonMark spec about what urls work as an autolink.

Fix detecting autolinks in unescape-links.mjs.

---

package.json
src/build/check-links.mjs

Slightly streamlines local link testing -- with this you can just do a `yarn run test:links` and test links locally.
Also changes check-links to *always* print the output report to the console -- not just on failure.

Add local link testing all-in-one command

---

src/components/CardCareers.vue
src/pages/Use.vue
src/templates/VueArticle.vue

This (hopefully) fixes the root cause of #758 by using `<div>`s to insert Markdown into Vue templates instead of `<p>`s.

Fix #758 for good (hopefully) by using <div>s to insert Markdown.

---

src/layouts/Default.vue

fd50bef tried to fix #1033 by changing headings to inline-blocks. But then when there's several headings in a row, they end up getting bunched up on the same line.
#1024 is another failed fix.
This PR proposes reverting to the old behavior until we find a solution that doesn't just introduce other problems.

Change headings back to blocks, not inline-blocks.

---

src/components/ArticleHeader.vue

Trying to address #976 by preventing titles from getting squashed by images, and images from taking up enormous vertical space.
This adds a clearfix below the header image so the title is sure to be below it if both can't fit in the same vertical space.
It also sets a max-height of 400px for header images.

Prevent conflicts between article titles and header images.

---

content/covid19/footer.md

I got the logos to be a manageable size and the container element to be larger than its contents.
But I did it by making the logo heights uniform, while at their ideal sizes their heights are slightly different.
Also, there's not much spacing between the logos. I'm not sure the best way to go about increasing it.

Convert COVID-19 logos footer into Markdown.

---

package.json
yarn.lock

This resolves warnings one might see with @babel/present-env not having the core peer dependency.

Add babel-core peer dependency

---

content/events/gcc2022/header.md

This fixes the #1075 bug in most GCC 2022 pages by removing HTML in the header Insert.
I'm not certain the exact HTML it was objecting to but one thing I noticed is that removing a single `<br />` from one version (so that there were no `<br />`s in the header at all) was enough to go from bug to no bug.
/events/gcc2022/schedule/ is still broken here - that seems to be an additional issue.

Fix most GCC 2022 pages by minimizing HTML in header.

---

cypress/integration/main.spec.js
src/index.html

This fulfills #785 by removing the dependency on jQuery and the Bootstrap plugins `<script>` (both sourced from unpkg.com). Based on the changes coming in #1102, the pages using this functionality are now deprecated.
It also removes the Cypress tests for this functionality.

Remove jQuery and bootstrap <script>s from index.html.

---

src/assets/styles.scss
src/layouts/Default.vue

Fix the current (build-only) issue where the font color in code blocks is dark on a dark background.
It looks like the issue was the order in which the styles were concatenated. Moving our `pre` style to `styles.scss` fixes the order.

Fix <pre> code block font colors.

---

src/components/ArticleHeader.vue
src/components/Redirect.vue
src/pages/404.vue
src/utils.js

This compartmentalizes all the redirect logic of the 404 page and pages with a `redirect` property into a Redirect component.
It also adds a "Cancel" button so the user can stay on the page if they wish. This can be useful in many situations, for example #1116 where a page is deprecated and redirected, but the user still wants access to the content.

Redirect component and cancel button

---

config.json
src/components/ArticleHeader.vue

Forgot to update the `config.json` in #1125. Caused the "Back to Covid19" links at the top to disappear.

Fix category path for covid19 pages.

---

src/layouts/Default.vue

The site-wide footer was bunching up and overlapping the bottom of the article contents on very small screens.

Fix site-wide footer layout.

---

config.json
src/components/ArticleHeader.vue
src/templates/Article.vue
src/templates/VueArticle.vue
src/utils.js

This adds Twitter and Open Graph `<meta>` tags to the `<head>` of pages with the proper metadata.
Fixes #1145.

Add social preview <head> meta tags.

---

src/build/partition-content.mjs
src/components/MarkdownEmbed.vue
src/main.js

Use it similar to `vega-embed`:
```
<markdown-embed href="https://raw.githubusercontent.com/galaxyproject/galaxy/dev/client/README.md" />
```
This will load that markdown, process it, and inject it in the page inheriting all the expected styles, as seen here, where I inject that client readme into my personal hub page with the line above:
(I really should update my person page, now that I see it...)

Remote markdown render

---

package.json
yarn.lock

Update url-parse to 1.5.10 due to [security issue](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-0512).
Closes #1188.

Bump url-parse.

---

content/usegalaxy/welcome/main.md

Two issues:
1. The alert box is at the very top of the page with no margin
2. Markdown links aren't converting, but in earlier drafts they were.

usegalaxy.org welcome page: Add text for Ukraine support

---

README.md
src/build/preprocess.mjs
src/build/run.mjs

Should fix #748 and #1207.
Bottom line: Copy all content files into the build directory instead of symlinking any of them. Unless we're doing `gridsome build` and it's a non-Markdown file.
For more detail, see discussion at the bottom of #1207.

Default to copy for preprocessing, except resource files on build.

---

content/community/coc/index.md

This PR updates the content of the CoC based on the discussions in the google doc. I made some extra adjustments:
- Included a sentence at the beginning stating what the CoC is (thanks Gareth for the suggestion).
- Reporting
- Creation of a form for (anonymous) reporting. Inspiration taken from the Bioconductor community.
- Creation of a mailing list for the members of the committee and added it as an option to report.
- Committee
- Included the members of the CoC in a table with emails embedded. Please fix the content as needed.  
- After meeting the Bioconductor CoC committee, added Laurent Gatto as ombudsperson and a couple of sentences explaining when to contact the Ombudsperson.
- Moved the historical note to the end to give some context to this change.

Update the Galaxy Code of Conduct

---

content/events/2022-02-04-VIB/index.md
src/layouts/Default.vue
src/pages/404.vue
src/pages/Blog.vue
src/pages/Careers.vue
src/pages/Events.vue
src/pages/Index.vue
src/pages/News.vue
src/pages/Search.vue
src/pages/Use.vue
src/pages/community/Devroundtable.vue
src/pages/events/Archive.vue
src/pages/events/Cofests.vue
src/pages/events/Webinars.vue
src/pages/events/cofests/Papercuts.vue
src/pages/usegalaxy/Welcome.vue
src/templates/Article.vue
src/templates/Platform.vue
src/templates/VueArticle.vue

Use [fragments](https://graphql.org/learn/queries/#fragments) to reduce duplicated GraphQL query code.
This also finally fixes GraphQL code indentation (to 4 spaces).

Use GraphQL fragments

---

content/tutorials/ngs/index.md

I know this page is deprecated but it's still in the top 10 most visited pages. And it's the 3rd result when you Google "galaxy sanger". It'd be nice if the first thing users see isn't a misspelled title.

Fix typo in title of /tutorials/ngs/

---

src/pages/Index.vue

Proposed change for Get Started button to make it clearer for newcomers where to go. Get Started could be understood as a instalation guide or "setting up your own galaxy instance" kind of guide.
@NickSto what do you think?

Change get started button to Get Started: First Steps with Galaxy

---

config.json
content/0examples/non-vue/index.md
content/0examples/vue-remark/index.md
content/eu/events/main.md
content/us/events/gcc2013/linktest.json
content/us/events/main.md
gridsome.server.js
src/assets/styles.scss
src/layouts/Default.vue
src/pages/eu/Events.vue
src/pages/us/Events.vue
src/templates/Article.vue
src/templates/Platform.vue
src/templates/VueArticle.vue
src/utils.js

This adds the barebones start of the subsites feature for the Hub unification effort.
It adds a `subsites` metadata key, the `us` and `eu` subsites, events pages for both, and a method for customizing the styling of pages in different subsites.
With this merged, we'll already be able to mark events with different subsites and they'll appear on the proper events listings.

Add some basic infrastructure for subsites.

---

content/events/2021-11-gi/index.md
content/events/2022-03-genome-assembly/index.md
content/events/2022-03-microbial/index.md
content/news/2021-08-elixir-update/index.md
content/news/2021-10-bycovid/index.md
content/news/2021-11-omicron/index.md
src/pages/eu/Events.vue

I thought I'd start tagging some events and news posts as `eu` or `us`, both to give the subsites logic some example data to work with and to start the discussion on what sorts of posts we want to categorize into specific subsites.
It was tricky to find clear examples of a "US" or "EU" post, since most events and news posts are trying for global reach. I don't particularly care if everything ends up being listed as global, so that's okay. From what I understand, the idea of making subsites in the first place was to allow us to have one, unified Hub while still letting people from different sites manage their own posts and content if they'd like. So we'll still maintain that option even if everything is global at first.
Also, a note: the posts I tagged as `eu` are basically duplicates also …

Start categorizing posts by subsite

---

content/projects/covid19/index.md

Guess that embedded markdown was just an accident.

Covid project: Remove client build instructions

---

config.json
gridsome.config.js
gridsome.server.js
src/templates/Article.vue
src/templates/VueArticle.vue
src/utils.js

So far I've only implemented two top-level subsites: `eu` and `us`.
But the .eu Hub itself has a set of subsites (`freiburg`, `pasteur`, `elixir-it`, etc). And, their main feeds (e.g. [/events](https://galaxyproject.eu/events)) aggregates all the posts from all their subsites.
Since we'd like to support the existing .eu Hub as much as possible, we'd like to preserve this organization but also add on top of it "global" aggregation pages which list all posts under the `us` and `eu` subsites, which might themselves aggregate posts from sub-subsites.
So this lets us define a hierarchy in `config.json` like:
```json
"subsites": {
"us": {},
"eu": {
"freiburg": {},
"pasteur": {},
"belgium": {},
"ifb": {},
"genouest": {},
"erasmusmc": {},
"elixir-it": {}
}
},
```
And during build it inspects the …

Allow hierarchical subsites

---

content/support/account-quotas/index.md

Through this Pull Request, I'm updating the content of [Find Histories that have been shared with you, and unshare those not needed](https://galaxyproject.org/support/account-quotas/#find-histories-that-have-been-shared-with-you-and-unshare-those-not-needed) in the Hub with that of [Unsharing unwanted histories](https://training.galaxyproject.org/training-material/faqs/galaxy/histories_unsharing_histories.html) in the GTN.
Kindly suggest any improvements or amendments.

Updated Unsharing Unwanted Histories

---

content/support/download-data/index.md

Removing part of the FAQ of downloading datasets using the command line.

Removing FAQ - Dataset download using Command line

---

content/support/tool-help/index.md

Removing this FAQ and replacing with the GTN link

Removing FAQ- Where is my Tool Help?

---

content/support/download-data/index.md

I noticed that I had not removed the part about Dataset collections and it is included in the same FAQ

Removing FAQ Download Dataset collection using command line

---

config.json
gridsome.server.js
src/components/NavBar.vue
src/layouts/Default.vue
src/templates/Platform.vue
src/utils.js

Previously, we made some assumptions that, say, the EU subsite would want to list every event happening in any of its lower-level subsites like Freiburg. And the same for Global vs. EU (or US). But, as discussed in #1317, that's not always what we might want.
So instead, this implements a new, simpler system where a post will only appear on the subsites it explicitly lists. To make it less tedious, you can use shorthands for certain sets of subsites instead of having to list every one. Currently there's just the `all` shorthand, which will expand to every current subsite. Shorthands are configurable in `config.json`.
Side note: This also renames the top-level subsite from `root` to `global`, which I think is a better name, especially since authors will now have to use it more often. …

No more automatic propagation and crossposting between subsites.

---

content/events/2021-08-metaproteomics/index.md
content/events/2021-10-21-anz-pacbio/index.md
content/events/2021-10-28-anz-pacbio/index.md
content/events/2021-10-eosc-gtn/index.md
content/events/2021-10-proteomics/index.md
content/events/2021-11-ausbiocommons/index.md
content/events/2022-01-abims/index.md
content/events/2022-01-small-scale/index.md
content/events/2022-02-proteomics-lfqanalyst/index.md
content/events/2022-03-small-scale/index.md
content/events/2022-04-Misconceptions-Writeathon/index.md
content/events/2022-05-small-scale/index.md

Some pages with only one tag listed it without brackets, which led to it being parsed as a string, not a list. It still worked, but it's not bad to be more explicit.
Also, some pages with no tags left the value blank instead of empty brackets. Again, no big deal but why not fix it while I'm at it?

Standardize `tags` values a bit.

---

src/components/ArticleTable.vue
src/components/ArticleTableBlog.vue
src/components/ArticleTableEvents.vue

And add an icon indicating which posts are external.
This just affects events, news, and blog posts.

Make external links to posts on other sites open in a new tab.

---

config.json

We'll probably want to post things to all the EU subsites but not the US one relatively often. This saves typing out all the EU subsites.

Add an `all-eu` subsite shorthand.

---

gridsome.server.js

This implements Option 2 of #1334.
In brief, this surfaces the `main_subsite` key to users. This lets an author define a primary subsite to display in the UI for a post, even if it's not under that subsite's url path.
It also cleans up some of the mess that `nodeModifier.processNonInsert()` has become by moving some of it to separate functions.

Let authors set a primary subsite.

---

content/belgium/main.md
content/elixir-it/main.md
content/erasmusmc/main.md
content/eu/main.md
content/freiburg/main.md
content/genouest/main.md
content/ifb/main.md
content/pasteur/main.md
content/us/main.md
gridsome.server.js
src/components/NavBar.vue
src/components/pages/SubsiteHome.vue
src/pages/Index.vue
src/templates/Platform.vue
src/utils.js

This adds a basic homepage for each subsite. It lists the news and events for each subsite and has some boilerplate static text. Intended to be a starting point for customization and a non-404 destination for the subsite navbar links.

Add subsite homepages

---

src/build/check-links.mjs

Mainly just making the table line up better in the terminal.

Tweak the formatting of the output text of the broken link checker.

---

src/components/ItemListBrief.vue
src/components/pages/SubsiteHome.vue
src/pages/Index.vue

Accidentally left the homepage showing news and events from all subsites, instead of just `global`.
This also hides and deduplicates some of the logic for showing Articles in a HomeCard.

Fix homepage news/event filtering, simplify HomeCard logic.

---

src/components/NavBar.vue

Putting the subsites in the NavBar advertises them *very* prominently. But the links to the different subsites lead to pretty empty homepages. Maybe let's wait to advertise them until it looks less beta.

Hide subsites for now

---

content/support/download-data/index.md
content/support/index.md

I was confused about removing this FAQ because it was a link to an external blog and addressed moving datasets and histories which I only addressed the datasets part but after exploring the GTN FAQs I found a similar FAQ about [moving histories](https://training.galaxyproject.org/training-material/faqs/galaxy/histories_transfer_entire_histories_from_one_galaxy_server_to_another.html) that addressed what was in the history section of the external [blog](https://genomicsvirtuallab.wordpress.com/2016/07/13/moving-data-between-galaxy-instances/). So, I renamed it "moving datasets..." and only linked it to the moving datasets GTN FAQ page. 
However, The link has also been mentioned multiple times throughout the FAQ page which I'm not sure if its necessary (I included all of it just incase) and …

Removing Moving Dataset between Galaxy Servers

---

content/eu/data-policy.md
content/footers/eu.md
content/hosted/usegalaxy-eu/jobs.md
content/hosted/usegalaxy-eu/main/jumbotron.md
content/hosted/usegalaxy-eu/main/main.md
content/hosted/usegalaxy-eu/notices/ukraine.md
src/pages/hosted/usegalaxy-eu/Main.vue

This replicates the middle pane of usegalaxy.eu, currently hosted by the EU Hub at https://usegalaxy-eu.github.io/galaxy/
I decided on the path `/hosted/usegalaxy-eu/main/`, so we can host the other EU middle panes under `/hosted/usegalaxy-eu/` and the usegalaxy.org middle pane under `/hosted/usegalaxy-org/`.
The only thing missing is the carousel, which we're probably replacing anyway.
Also I just couldn't get the footer to be flush with the bottom of the page, so I omitted the `background-color` since that highlighted the gap.

Implement usegalaxy.eu middle pane

---

content/events/2021-05-27-dev-roundtable/index.md
content/events/2021-06-10-dev-roundtable/index.md
content/events/2021-07-22-dev-roundtable/index.md
content/events/2021-08-19-dev-roundtable/index.md
content/events/2021-10-28-dev-roundtable/index.md

Looks like there's an accidental newline breaking up an attribute string.

Fix malformed Youtube embed in some Dev Roundtable pages.

---

src/components/Gitter.vue
src/index.html
src/layouts/Default.vue

This moves the Gitter chat embed out of the global index.html, so that we can avoid having it in certain pages (like BareArticles).
This addresses the double-gitter embed issue with #1365. Now, the BareArticle won't have it by default, so it won't appear in the inner BareArticle iframe (the news/events). But we *do* want it in the outer BareArticle, which can be done by including the `<Gitter />` component in its Markdown.
I think this avoids the race condition from #806, since it manually loads the Gitter JS only after setting the needed global variables. But it could certainly stand a second pair of eyes.

Move Gitter chat embed from index.html to its own component.

---

content/bare/usegalaxy-eu/main/index.md

Use #1367 to add Gitter chat to `/bare/usegalaxy-eu/main/` (but not its iframe).

Add Gitter chat back to usegalaxy.eu middle pane.

---

src/pages/bare/eu/Latest.vue

Lack of `scoped` property on the `<style>` was causing the `<a>` font color to be global. This made, for example, the Gitter chat button text blue in Chrome.

Scope link color style in /bare/eu/latest/.

---

content/events/gcc2022/schedule/index.md

I finally hunted down the #1075 bug in the schedule page. It looks like it was actually the lack of an explicit `<tbody>` in the table(!)
Fixes #1103

Fix #1075 bug in GCC 2022 schedule page

---

src/components/NavBar.vue

It could be improved aesthetically, but this addresses the issue (#1363) and should work on any background color a subsite chooses (it uses transparency).
Fixes #1363.

Make hamburger menu on mobile NavBar more visible.

---

src/components/NavBar.vue

A much better fix than #1378 for #1363.
Uses the native `type` property of `<b-navbar>` to set the theme to dark or light, based on subsite metadata (`lightBg`). This results in a hamburger button that perfectly fits in:

Better fix for hamburger button visibility.

---

src/assets/styles.scss

@NickSto This is what I mentioned; the shim works for maintaining compatibiltiy when importing and we can update selections over time.

Add fontawesome shim for compatibility

---

src/pages/bare/eu/Latest.vue

Make our CSS rule take precedence.
Before it was at the same level as bootstrap's.
\- Depended on who got loaded last, which changes between develop/build.

Fix to left side of latest posts BareArticle getting cut off.

---

config.json
gridsome.config.js
package.json
src/build/toc-add.mjs
src/utils.js
yarn.lock

This recreates the EU [RSS feed](https://galaxyproject.eu/feed.xml) as closely as possible, using [gridsome-plugin-feed](https://gridsome.org/plugins/gridsome-plugin-feed).
The resulting feed is located at https://galaxyproject.org/eu/feed.atom (the .eu one is actually Atom, not RSS).
The resulting XML isn't an exact replica of the .eu one, due to limitations of gridsome-plugin-feed, but it's very close. Basically, there are a handful of tags and attributes that I wasn't able to include. I figure the plugin knows enough to produce a valid feed (it's using the [feed](https://www.npmjs.com/package/feed) npm package), but once it's live I'll test it in an RSS reader (if I can unearth one).
| parent | tag |
|--------|-----|
| `<entry>` | `<published>` |
| `<entry>` | `<category>`  |
| parent …

Implement EU RSS feed

---

content/news/2022-05-gcc2022-call-for-bofs/index.md

The url and one link still accidentally said GCC 202**1**.
This does change the url but it hasn't been up for long so I assume we don't need to redirect.
CC @tnabtaf

GCC2022 Call for BoFs: fix a couple references to GCC 2021

---

config.json

Added during development of #1397, but didn't end up using it.

Remove leftover config.json key added briefly during RSS development.

---

gridsome.config.js
src/build/partition-content.mjs
src/lib/utils.js

#1365 made it possible for collections defined in `config.json` to use `vue-remark`. But the Partitioner in `partition-content.mjs` still used the old rules for placing Markdown files in `build/content-md` or `build/content-vue`. These rules were based on inspecting the Markdown file, not where it's placed. So it was possible to define a `vue-remark` collection but one of the pages wouldn't appear because it doesn't contain any Vue components, so the Partitioner put it in `build/content-md` instead of `build/content-vue`, where the collections looks for its content.
The immediate effect was that pages in `/bare/` would become `Article`s instead of `BareArticle`s if they didn't contain any Vue components.
This updates the Partitioner so it checks the path of the `index.md` file against the …

Fix issue with partitioning user-defined Collections

---

content/events/2022-05-26-community-call/index.md

Justification for changing phrase: The first time the content came first and the updates second, but that felt odd. The second time we presented community updates first, then content. This allows some flexibility in how it's handled.  It seems I'll be chairing this meeting, and will probably do the community updates first.

adding zoom link, modifying one phrase

---

src/components/NavBar.vue

For now add the Covid19 and the MPXV efforts to it.
The idea is that projects listed under https://galaxyproject.org/community/wg/#current-set-of-projects should all have hub pages, then be added to the menu.

Add a Projects menu to the NavBar

---

cypress/integration/main.spec.js
src/templates/VueArticle.vue

Instead, use .insert class to label them.

Remove redundant .markdown class from Insert containers

---

src/components/Redirect.vue

This eliminates one annoying console warning.

Give an accurate type for Redirect.vue's `location` prop

---

content/0examples/vue-remark/index.md

This adds some usage examples for using Vue components and frontmatter metadata in Markdown content.

Add more documentation on some vue-remark features.

---

content/events/2022-05-19-elixir-belgium/index.md
content/events/2022-05-25-biodiversity/index.md

#1433 attempted to fix an issue where two articles got tagged with the nonexistent subsite `vib` by removing the tag, since it was already tagged with `eu`. I forgot that meant it wouldn't actually show up on the VIB subsite, as was clearly intended. This adds the proper subsite, `belgium` back to them.

Assign correct subsite metadata to a couple articles

---

content/events/archive/main.md

Somehow the link to [/events/archive/wayback/](https://galaxyproject.org/events/archive/wayback/) had gotten deleted.

Restore link to pre-2016 events archive.

---

content/hub/history/index.md

I wanted to record some development history of this project that isn't captured in existing PRs, issues, and documentation. Why not keep it on the Hub itself?

Start a page documenting Hub development history.

---

src/templates/BareArticle.vue

Do to `BareArticle`s what #1430 did for `VueArticle`s.

Remove redundant .markdown class from BareArticles too.

---

src/build/fix-links.mjs
src/lib/utils.js

This addresses an error which can arise in fix-links.mjs in the unusual situation where the url on a [node](https://github.com/syntax-tree/mdast) is undefined. Now, instead of crashing the build, this will print a useful warning, leave the link unaltered, and continue.
This error was discovered in #1437, being caused by something in the large svg blob in [content/projects/ppandemic/s1e1/index.md](https://raw.githubusercontent.com/galaxyproject/galaxy-hub/d1a2ccb4e12d23570f1be56952b32e7e712e56f6/content/projects/ppandemic/s1e1/index.md).

Handle undefined/null urls in fix-links.mjs.

---

src/templates/Article.vue
src/templates/BareArticle.vue
src/templates/Platform.vue
src/templates/VueArticle.vue

Add a class at the root of each Collection template labeling which collection it is. This is helpful for development, to quickly identify which collection is displaying any particular page. It can also be used for styling.

Label each collection with a class

---

content/belgium/cards.md
content/elixir-it/cards.md
content/erasmusmc/cards.md
content/eu/cards.md
content/freiburg/cards.md
content/genouest/cards.md
content/ifb/cards.md
content/pasteur/cards.md
content/us/cards.md

On subsite homepages, the "News" and "Events" headings at the top of the list of news/events posts linked to the global /news/ and /events/ pages, instead of the subsite pages.

Fix links on subsite homepages to subsite News and Events.

---

src/components/pages/Events.vue

#1467 fixed the layout of the table of contents with a global CSS style, but that also requires a clearfix in the HTML to work properly. I did that in the body of Markdown pages, but I also used the ToC classes in a dynamic page (Events.vue). This adds the clearfix to that.

Fix layout of ToC/body on Events.vue.

---

content/bare/eu/events/main.md
content/bare/eu/news/main.md
src/pages/bare/eu/Events.vue
src/pages/bare/eu/News.vue

Add replacements for [/galaxy/news.html](https://usegalaxy-eu.github.io/galaxy/news.html) and [/galaxy/events.html](https://usegalaxy-eu.github.io/galaxy/events.html).
Progress toward #1479.

Add /bare/eu/news/ and /bare/eu/events/

---

content/projects/covid19/index.md

The extra `</div>` was closing the `.body-wrapper` div, messing up the layout and causing a return of #1467.

Remove extra </div> from covid19 homepage.

---

src/lib/utils.js

Adding a method I've had to rewrite multiple times when debugging remark plugins like toc-remodel.mjs.

Add summarizeMdNodes() method for debugging

---

content/bare/usegalaxy-eu/metabolomics/index.md

#1491 removed /bare/eu/latest/ and added /bare/eu/latest/news/ and /bare/eu/latest/events/. It replaced the former in the usegalaxy.eu middle pane, but left one reference to it in metabolomics.usegalaxy.eu.

Replace /bare/eu/latest/ in the metabolomics middle pane too

---

src/pages/bare/eu/latest/Events.vue
src/pages/bare/eu/latest/News.vue

Similar to #1485 but for /bare/eu/latest/news/ and /bare/eu/latest/events/

Fix links to /news/ and /events/ in /bare/eu/latest/ pages.

---

content/eu/twitter-card.md
content/twitter-card.md
src/components/Twitter.vue
src/components/pages/SubsiteHome.vue
src/lib/client.mjs
src/pages/Index.vue

The method we were using to embed the Twitter timeline on the homepage was long deprecated. This updates it to use the current method.
This also adds a `<Twitter>` component to allow embedding timelines in Markdown pages (or anywhere).

Update Twitter timeline widget, add component

---

config.json
content/bare/eu/usegalaxy/main/index.md
content/bare/eu/usegalaxy/metabolomics/index.md
content/bare/eu/usegalaxy/proteomics/index.md
src/components/Gitter.vue
src/layouts/Default.vue

Previously, the Gitter component always opened the main "galaxyproject/Lobby" room. But EU has its own room (usegalaxy-eu/Lobby), and that's what they use on their Galaxy middle panes.
This adds a `room` prop to the `<Gitter>` component, and uses it to specify the EU room in the current middle panes. This also uses the appropriate room on all subsite pages. Each subsite can set its own room through config.json's subsites.metadata list.

Allow specifying a different Gitter room

---

src/components/pages/SubsiteHome.vue
src/lib/pages.mjs
src/pages/Index.vue

Previously, if an author added a new subsite to config.json, then visited its homepage, they would get a 404 or an error.
This makes a blank homepage appear instead. It also prevents errors if some of the essential Inserts (main.md, cards.md, etc) are missing but not others.
This is sorta progress towards #1526.

Prevent error when visiting blank subsite homepage.

---

config.json
gridsome.server.js
src/components/Gitter.vue
src/components/NavBar.vue
src/layouts/Default.vue
src/lib/site.js
src/lib/utils.js
src/templates/Platform.vue

Implement #1421.
Only difference from what #1421 proposed: `subsites.metadata` is renamed to `subsites.all` (instead of `subsites.list`, which could be confusing, since it's an object, not an array).

Remove subsites.hierarchy from config.json

---

src/components/pages/Events.vue
src/components/pages/EventsArchive.vue
src/components/pages/News.vue
src/components/pages/SubsiteHome.vue
src/lib/pages.mjs

This follows up on #1527 by also making sure the other auto-generated subsite pages besides the homepages will work out of the box: `/{subsite}/news/`, `/{subsite}/events/`, and `/{subsite}/events/archive/`.
This also uses better defaults for missing data. Namely, the page title will use the human-readable subsite name instead of the raw key.

Improve behavior when a new subsite is added to config.json

---

content/usegalaxy/welcome/main.md

When I went to Galaxy, for a second my brain saw the big red notice and it looked like it was saying Galaxy itself was being shut down.
This bolds the word "FTP" as a feeble attempt to reduce the likelihood of that happening.

FTP decomission notice: emphasize that it's only the FTP service.

---

gridsome.config.js
package.json
yarn.lock

Useful for multiple things, including progress toward #1442

Add a basic sitemap

---

src/components/NavBar.vue

Before:
[![image](https://user-images.githubusercontent.com/645773/184006143-d1d033d8-fcf2-4e3c-a3b2-af052f6f3e3e.png)](https://galaxyproject.org/erasmusmc/)
After:

Center subsite names in the NavBar.

---

navbars.json
src/components/NavBar.vue
src/components/NavBarItem.vue

This changes the NavBar from being entirely hardcoded and site-wide to making it partially configurable by each subsite.
Each subsite can define their own navbar in the `navbars.json` config file. I tried to make the format as intuitive as possible.
FYI this doesn't yet support the `<b-dropdown-group>` component used in #1429, so if we end up wanting that we'll have to extend this.

Customizable navbars

---

navbars.json

I think "Help" is a better description of what you'll find under the current "Support" dropdown. To me, "Support" suggests more like live software support, but the things in the dropdown are more like self-help resources.
It also gives us just a smidge more room in the navbar, which really matters at this point.
Before:
After:

Rename "Support" NavBar dropdown to "Help".

---

src/assets/styles.scss
src/components/NavBar.vue

This adds a few convenience classes so you can easily mark an element to only show on larger screens.
For example, this PR also includes a change using the new system to hide the "Edit" label on the NavBar Github link when the screen width gets below 1200px (it was bunching up and causing layout issues). It does this by just adding the `xl-plus` class to it. The class names use Bootstrap's [size names](https://getbootstrap.com/docs/5.0/layout/breakpoints/): `sm-plus`, `md-plus`, `lg-plus`, and `xl-plus`.

Add classes for hiding elements on small screens.

---

cypress/integration/main.spec.js
src/components/NavBar.vue

This shrinks the search box when the screen starts getting narrow and we start really running out of space in the NavBar.
It expands it again once the screen gets truly mobile-size because then the NavBar collapses to a hamburger dropdown, where we have more horizontal space for each item again.

Fine tune NavBar search box size on different screen sizes

---

src/components/NavBar.vue
src/components/pages/SubsiteHome.vue

When navigating between subsite homepages (ones that use `SubsiteHome.vue`), most of the content fails to update.
This is because many of the data structures those pages use are defined in the `created()` hook, which doesn't run between navigations because the page doesn't get re-created. Instead, we have to use the `beforeUpdate()` hook, which runs [just after the page data changes](https://vuejs.org/guide/essentials/lifecycle.html#lifecycle-diagram).

Fix issue navigating between subsite homepages

---

src/index.html
src/layouts/Default.vue

Probably fixes https://github.com/galaxyproject/galaxy-hub/issues/1436
(to be clear -- not opposed to plausible, whether paid or self-hosted, but this definitely seems like the immediate path of least resistance to keep the tags working fine for now)

Swap to new GA4 tag

---

gridsome.server.js
src/components/NavBar.vue

The original implementation (#1589) differentiated different classes of `Dataset`s by making a `type` attribute defined by custom code in `gridsome.server.js`.
Instead let's just use the name of the yaml file and say that defines the type of Dataset. We get this for free: there's already an automatic `filename` attribute on each node. And it's more transparent and intuitive for authors as well.

Datasets: use existing filename attribute instead of "type"

---

config.json
content/elixir-it/navbar.yml
content/erasmusmc/navbar.yml
content/eu/navbar.yml
content/genouest/navbar.yml
content/ifb/navbar.yml
content/pasteur/navbar.yml
content/us/navbar.yml
gridsome.server.js
package.json
src/components/NavBar.vue

Now the navbar customizations are all in one place: the navbar.yml files.
This also allows authors to let sections of the NavBar default to the global items by just omitting the sections in the yaml.

Move the NavBar styling info from config.json to the navbar.yml files

---

src/lib/pages.mjs
src/lib/utils.js

#1600 introduced `lodash` as a dependency, so now we can replace one of the utils.js functions with their version.

Replace utils.js `shrinkWrap()` function with `compact()` from lodash

---

src/build/partition-content.mjs

The `fileRequiresVue()` function in `partition-content.mjs` contained a periodically-growing, hardcoded list of components it searches Markdown files for. This list was out of sync with another list that was in its docstring.
This updates the documentation and puts the hardcoded list in a constant, at least. It still feels like these should go in `config.json` or something. But there's another duplicate list of the global components in `main.js`, and it's a lot harder to source that one from `config.json`. But at least this reduces the number of duplicates by one.
This also tweaks the autodetection algorithm by removing the requirement for the tag to have a space after it (e.g. it looks for `<slot`, not `<slot ` now). This could save a future headache if we end up in the situation where …

Put list of components autodetected by `fileRequiresVue()` into constant, tweak algorithm

---

content/0examples/non-vue/index.md
content/0examples/vue-remark/index.md
src/components/ArticleHeader.vue
src/templates/Article.vue
src/templates/VueArticle.vue

This field allows an author to show the tease in the listing page (`/news/`, `/events/`, etc), but hide it on the Article/VueArticle's actual page.
This is useful in cases like when we're importing content from .eu which doesn't have a tease, so we just use the first sentence of the content. That works, but looks repetitive when it shows up twice in a row on the article's page. So this works around that issue.

Add `hide_tease` metadata field

---

content/usegalaxy/welcome/main.md

Update to the same post-GCC image as on the Hub homepage.

Update GCC image on usegalaxy.org middle pane

---

config.json
src/components/NavBar.vue

This makes it so the list of subsites in the NavBar "Regions" drop-down is stored in the `subsites.navbar` key of config.json, instead of using the `order` property of each entry in the `subsites.all` list. It duplicates the subsite keys again, but it seems a bit more natural to store the order in an array instead of indices of properties of objects. It also makes it more explicit what the setting is for, and allows omitting subsites too.
One visible change this makes is that it now shows the current subsite in the list instead of omitting it. I think this makes navigation a bit easier, and it's also consistent with how the rest of the NavBar links work.

Change how NavBar subsite dropdown menu order is stored.

---

content/events/2020-03-wir-vs-virus/index.md
content/events/2020-06-ml/index.md
content/events/2020-12-metabolomics/index.md
content/events/2021-01-metabolomics/index.md
content/events/2021-09-arc/index.md
content/events/2022-08-16-eurosciencegateway-kickoff-meeting/index.md
content/events/2022-09-29-community-call/index.md
content/events/2022-09-small-scale/index.md
content/events/2022-10-13-community-call/index.md
content/events/2022-10-27-community-call/index.md
content/events/2022-10-cloud-computing-workshop/index.md
content/events/2022-11-BH2022/index.md
content/events/2022-gcc/index.md
content/events/2022-pag/index.md

Until we do an automated change of all `location_url` metadata fields to a `url` property of the `location` field (details in #1621), this makes that change for some recent events. That should help people using them as a template.
This also removes fields with empty values from recent events, too.

Remove empty metadata fields, change location_url -> location.url

---

src/components/NavBar.vue

This enables the NavBar "Regions" dropdown menu for switching between subsites, but only for the new (non-Global) subsites.
Since the non-Global subsites aren't accessible* yet, this doesn't really make them public yet. So it's not the official unveiling yet. It just makes it easier to test and preview what it'll eventually look like.
\* The exception is that there's a few events with a `main_subsite` set, which makes the navbar for that subsite display. But there's only two at the moment. Call it a "stealth launch" if you want.

Enable Regions dropdown for subsites other than Global

---

src/components/HomeTop.vue
src/lib/pages.mjs

This reworks `gatherBundles()` and omits the HomeTop component when it's empty. This has the effect of, for instance, removing the excessive empty space below the title on the Pasteur homepage.

Rework how Bundles are gathered, don't include HomeTop when empty.

---

cypress/integration/main.spec.js

xref #1632; It's not worth the noise from the github action failures.

Drop gitter sidecar test 

---

content/us/navbar.yml

Because of the way NavBar defaults are inherited, the US navbar's "News" and "Events" links were to the Global feeds, not the US feeds. See #1635 for details.

Fix relative links in US navbar.

---

content/0examples/non-vue/index.md
content/0examples/vue-remark/index.md
src/components/ArticleHeader.vue
src/components/ArticleTableEvents.vue
src/components/Contacts.vue
src/components/pages/Events.vue
src/components/pages/EventsArchive.vue
src/components/pages/TaggedEvents.vue
src/templates/Article.vue
src/templates/VueArticle.vue

This adds support for structured `contacts` to pages. This is mainly for compatibility with the `organiser` field in the .eu hub so we can preserve that data while porting in that content. It's related to the Community Directory effort (#1551) but it may or may not need to be altered once that goes live.

Display structured `contacts` metadata field

---

content/belgium/events/main.md
content/belgium/news/main.md
content/elixir-it/events/main.md
content/elixir-it/news/main.md
content/erasmusmc/events/main.md
content/erasmusmc/news/main.md
content/eu/events/main.md
content/eu/news/main.md
content/freiburg/events/main.md
content/freiburg/news/main.md
content/genouest/events/main.md
content/genouest/news/main.md
content/ifb/events/main.md
content/ifb/news/main.md
content/pasteur/events/main.md
content/pasteur/news/main.md

This adds a notice at the top of every European page with a full list of news or events:
The link is to the equivalent page on https://usegalaxy-eu.github.io.
I think we should have some kind of notice like this until we've migrated all (or most) of the .eu content.
This is part of the plan laid out in https://github.com/galaxyproject/galaxy-hub/issues/1480#issuecomment-1170362963.

Add pointers to .eu from pages without full list of news/events

---

package.json
src/build/partition-content.mjs
src/main.js
yarn.lock

This adds the [vue-tweet-embed](https://www.npmjs.com/package/vue-tweet-embed) package to allow easily embedding tweets and timelines.
keywords: twitter

Add vue-tweet-embed package

---

src/components/Flickr.vue
src/lib/client.mjs

Generally useful, and at least one .eu page uses a Flickr embed which won't otherwise work in vue-remark because it depends on a <script> tag in the Markdown.

Add Flickr component

---

content/bare/eu/usegalaxy/proteomics/index.md
src/build/partition-content.mjs
src/components/Twitter.vue
src/main.js

This is a rewrite of our `<Twitter>` component, instead of removing it as in #1642. This component wraps the `<Tweet>` and `<Timeline>` components from `vue-tweet-embed` (added in #1641).
This was mainly needed to prevent authors from having to continually repeat the double-div wrapper and custom styling necessary for centering the embeds. It also provided an opportunity to improve the interface. Particularly, this provides a single component for both individual tweets and timelines, instead of two separate components.

Replace existing Twitter component with a wrapper for the vue-tweet-embed ones

---

doc/AUTHORING.md
src/assets/styles.scss

Adding `.center` to the normal image wrapper `<div>` didn't work in the most common case where you're also resizing the image by width. Instead, an additional `<div>` is needed. This makes that double wrapper work (and documents it).

Add CSS rule to make centering images easier

---

src/components/ArticleHeader.vue

The "Contact:" field was showing in the headers of articles with no contacts.
Also, I missed a spot where the old contacts display was being used.

Fix bugs in contacts in article headers

---

src/assets/styles.scss

When you use the `.img-sizer` class, the result is a `<div>` with that class, with a `<p>` inside, and an `<img>` inside that.
Previously, the `<p>` retained its default spacing, so it had a `margin-bottom: 1rem` below the `<p>` and above the bottom of the `<div>`. This has been fine generally, but if you want to add a border to the `<div>`, it makes it look asymmetrical. This places the margin below the `<div>` instead.

Move margin below img-sizer images to outside the div

---

content/authnz/config/oidc/index.md

The Custos service address changed recently, and the url on the OIDC configuration example for Custos was outdated.
Similarly, several changes will be needed here: https://galaxyproject.org/authnz/config/oidc/idps/custos/

Update OIDC config - Custos url

---

src/pages/everywhere/Events.vue
src/pages/everywhere/News.vue

With the decision in #1317 to make every subsite only list posts tagged specifically for it, no current page, even the `global` ones, contains a full list of every post. This could be useful for various reasons. Right now, it's very useful in the .eu content migration process to make sure we have every one of their posts.
The urls are `/everywhere/news/` and `/everywhere/events/`. I'd have preferred to use `all` instead of `everywhere`, but that could get confused with the `all` subsite shorthand, which whose definition is whatever `config.json` says, so it doesn't necessarily mean the same thing.

Add pages listing every news and event post from every subsite

---

gridsome.server.js
src/components/pages/Events.vue
src/components/pages/EventsArchive.vue
src/components/pages/News.vue
src/components/pages/SubsiteHome.vue
src/components/pages/TaggedEvents.vue
src/pages/Blog.vue
src/pages/Index.vue
src/pages/bare/eu/Events.vue
src/pages/bare/eu/News.vue
src/pages/bare/eu/latest/Events.vue
src/pages/bare/eu/latest/News.vue
src/pages/everywhere/Events.vue
src/pages/everywhere/News.vue

This resolves #751 by creating a new Collection called `ParentArticle`. Each `ParentArticle` is created by copying the data from an `Article` or `VueArticle`. But FYI the "copies" are mostly just references to the same string objects, so there's not much memory overhead.
So dynamic pages can just query for `allParentArticle` instead of doubling the number of queries (one for `Article`s and one for `VueArticle`s). Since the GraphQL queries are the least dynamic part of the system, without this there's not much we can do to avoid hardcoding two copies of every query.
This was the least bad solution I found. I also [tried](https://github.com/NickSto/galaxy-hub/commit/93ddb29d97993069334a9b1baff178be5d338c02) creating a sort of inheritance through GraphQL interfaces, but I don't think …

List VueArticles in dynamic pages too

---

src/build/fix-links.mjs
static/assets

This adds a symlink from static/assets to content/assets so we can place images from .eu there and have them work with unchanged absolute urls like /media/assets/image.jpg. I also had to add /assets/ to the allowlist of urls which shouldn't be altered by fix-links.mjs.

Fix issues with using images in /assets/media/

---

content/events/2022-06-07-elixir-training-platform/index.md
content/events/2022-06-08-elixir-covid/index.md
content/events/2022-06-08-vhir/index.md
content/events/2022-06-09-community-call/index.md
content/events/2022-06-23-community-call/index.md
content/events/2022-07-07-community-call/index.md
content/events/2022-07-irods-user-group-meeting/index.md
content/events/2022-08-04-community-call/index.md
content/events/2022-08-18-community-call/index.md
content/events/2022-08-taiarapu-assembly-annotation/index.md
content/events/2022-09-01-community-call/index.md
content/events/2022-09-15-community-call/index.md
content/events/2023-02-ebi-single-cell/index.md
content/events/2023-04-sib-introduction/index.md
content/events/bcc2020/index.md

This adjusts the most recent events to use the newer, structured `location` metadata field instead of `location_url` as a separate field.
This should help people using existing events as a template.

location_url -> location.url on a few posts

---

content/eu/site-footer.md

A link like `<a rel="me" href="https://xn--baw-joa.social/@galaxyfreiburg">bla</a>` on the site will allow account verification on mastodon.
I hope I got the syntax right for getting the correct `rel` attribute.

Add .eu mastodon link

---

README.md
content/hub/contributing/file-organization/index.md
content/hub/contributing/index.md
content/hub/contributing/markdown/index.md
content/hub/dev/history/index.md
content/hub/global/index.md
content/hub/index.md

This expands the content in [/hub/contributing/file-organization/](https://galaxyproject.org/hub/contributing/file-organization/) with info about the Vue files for dynamic pages.
I also decided to try out breadcrumbs instead of the generic "back to home" at the top of the page. Maybe a bit of a prototype for #957?

Expand on file organization documentation, add breadcrumbs to Hub documentation pages

---

.github/workflows/optimize-images.yml

We will assume webp contributors will do this on their own -- calibre otherwise will sometimes repeatedly recompress the same webp.
xref #1761

Skip compression of webp in image compression github action

---

config.json
package.json
src/layouts/Default.vue
yarn.lock

Just an example; we can prune this back and only apply to a subset of pages if desired.
Can also add a button to disable them if we want, I guess.
If we want this on usegalaxy welcomes, I can add it there, too.  Then the instances get the snowflake treatment as well, automatically, without having to deploy anything specific to them.
https://user-images.githubusercontent.com/155398/207084535-979d6385-3151-4a3a-a220-6dd452215c6b.mp4

Snowflakes for the holiday season

---

content/belgium/navbar.yml
content/elixir-it/navbar.yml
content/erasmusmc/navbar.yml
content/eu/navbar.yml
content/freiburg/navbar.yml
content/genouest/navbar.yml
content/ifb/navbar.yml
content/jxtx/index.md
content/navbar.yml
content/pasteur/navbar.yml

Updates the masthead @jxtx link to go straight to the foundation.  Leaves all the local JXTX content in place, minor tweak to the main page in organization.

JXTX Tweaks

---

content/bare/eu/usegalaxy/main/index.md
src/layouts/Default.vue
src/pages/usegalaxy/Welcome.vue

Holiday break is (mostly) over; this disables the snowflakes.  (but leaves the component around for next time, or for reuse with koalas/etc)

Drop holiday season snowflakes

---

content/news/2022-03-25_add-storage-dashboard/index.md

This is a test PR that takes a PR description and creates a small news entry for it. The second commit is what the reviewer of this hub PR needs to do manually. The bulk of technical descriptions and images should already be there so that the hub reviewer only needs to clean up and bit and maybe simplify the sentences.
The date is taken from the pr-merge-date, so we can also create these posts retrospectively. There are some really good PR descriptions with (animated) images or even videos, I think they are good content for our general audience that we should re-use in the hub.
Any feedback and comments?

News entry for PR (13113): "Add Storage dashboard"

---

content/0examples/non-vue/index.md
content/events/gcc2023/index.md
src/components/ArticleHeader.vue
src/templates/Article.vue
src/templates/VueArticle.vue

Currently only used in the gcc2023 page; this new `hide_metadata` option for articles does that, deferring to the page author to convey whatever information they need.

Add the option to hide the metadata display on events pages when desired

---

content/news/2023-02-20-tlaas-training-infrastructure-as-a-service/index.md

https://www.eosc-life.eu/news/success-story-tlaas-training-infrastructure-as-a-service/ -> they write Tlaas (with L)but should be TIaaS (with I)

* added news item

---

content/bare/eu/usegalaxy/main/index.md

Added banner with link opening new tab:

Add GCC2023 banner to EU landing page

---

config.json
package.json
src/build/run.mjs

Webpack has stated they won't be fixing this in webpack4x, which we are stuck with w/ gridsome for now.  This workaround workaround works for me and allows building/serving/developing with node v18.
Edit: I need to look at what node version ubuntu-latest is using here and why it's yelling about that option being used, I haven't seen this in the Galaxy context before.  Might just be able to update base image and move on, but I'll follow up on this later (after the Galaxy freeze likely) -- no rush on the PR.

Fix openssl issue for webpack4 and node18

---

content/support/account-quotas/index.md
content/support/index.md

Trailing slash in the URL is leading to a 404 error.

Remove trailing slash in Lobby gitter chat URL (currently leads to a 404)

---

content/news/2023-03-15-new-history-search/index.md

I mistakenly linked `http://localhost:8080/news/2022-08-galaxy-release-22-05/` instead of `http://galaxyproject/news/2022-08-galaxy-release-22-05/`

Fix link in new history search news item

---

content/bare/eu/usegalaxy/notices.md

BWCloud is currently under maintenance and will last until tomorrow.
BWCloud notice: https://www.bw-cloud.org/de/news/2023/12-03-ankuendigung_wartung_bwcloud

Add BWCloud maintenance notice to EU

---

content/bare/eu/usegalaxy/notices.md

Maintenance is over and the services are back online.

Remove EU maintenance notice

---

content/bare/eu/usegalaxy/notices.md

This reverts the maintenance announcement in commit 0e1852dfdff6784bf92c1082a8bb571e0064a7c1 (but not the blog post).

Revert "Maintenance Announcement EU (#2031)"

---

content/events/gcc2023/conduct/index.md
content/events/gcc2023/covid19/index.md

Move "distancing badge" section to conduct page

---

.github/workflows/gtn-news.yml

GitHub Actions workflow that automatically creates PRs to publish Galaxy Training Network news as external links.
Closes #1417. Folow-up of #2065.
An example PR created by this workflow is available [here](https://github.com/kysrpex/galaxy-hub/pull/21). An example workflow run is available [here](https://github.com/kysrpex/galaxy-hub/actions/runs/5477340935).
This PR hopefully addresses all the feedback from #2065, namely:
- Post template (@bgruening)
- Include authors (@hexylena)
- Batch all posts in one PR (@hexylena)
In addition, the whole approach has been reworked. The workflow uses now just feedparser and the GitHub REST API (through GitHub CLI and curl). Hopefully it is significantly faster (I cannot compare since I deleted the repo) as it avoids checking out the code.

Automatically publish posts from GTN

---

.github/workflows/gtn-news.yml

The template of the GTN News workflow is wrong (news do not render). This PR fixes it.
Related: #2072.

GTN News workflow: fix broken template

---

.github/workflows/gtn-news.yml

The pull request creation is intended to fail when there are no changes to be merged, but it is better if it fails silently :)
```shell
pull request create failed: GraphQL: Head sha can't be blank, Base sha can't be blank, No commits between master and gtn-news, Head ref must be a branch (createPullRequest)
```

Prevent GTN News workflow from failing when there are no items to publish

---

content/news/2023-07-11-carbon-emissions-reporting/index.md

This PR adds github author information and increases the sizes of images in the carbon emissions reporting post.
An issue tracking the progress of the feature can be found in the Galaxy repo https://github.com/galaxyproject/galaxy/issues/15046.

Add github author and increase image size on carbon emissions post

---

content/bare/eu/usegalaxy/notices.md

Add a banner warning of potential disruption due to the upcoming Galaxy 23.1 upgrade on Sunday night (August 20th, CEST).
---
Temporarily replaces the "Handeln statt Kriminalisieren" statement banner.

Galaxy 23.1 upgrade banner

---

content/bare/eu/usegalaxy/notices.md
content/news/2023-09-11-climate-strike/index.md

After looking at the outcome of #2159, I think it is very confusing that two banners have the same color and more importantly, that the strike banner has no title.
In addition, thinking it twice I think it makes better sense to link to the page specific to the action on Friday rather than the main page of Fridays for Future.

Amend Galaxy EU 15.09.23 climate strike notification

---

content/cards.md
src/lib/client.mjs
src/pages/Index.vue

Drops (broken) twitter embed, expanding news and shifting events over to keep the grid intact.

Drop twitter embed

---

src/components/NavBar.vue

This pull request changes the navbar look in mobile view as shown below
please do add tags necessary for Hacktober Fest

modified navbar look for mobile view

---

src/index.html

It would be helpful for the rest of us to have live access to stats, like we do for the training website, to help us know what resources are getting accessed and if we can optimise them.
It wouldn't have to be public (though I'd strongly argue for it for transparency), but can also be shared with individuals via link.
(If i don't see complaints by the end of the week, I'll merge this.)

add plausible analytics

---

content/tutorials/collections/index.md

Redirect updated from /learn to link to the "Using dataset collection" tutorial instead.

Updating 'redirect' link for Galaxy connections

---

content/us/lead.md

_For experienced users, added "Use Galaxy" button that links directly to the list of servers page. Also added very basic source tracking so we know how helpful these buttons are._

Fix for link to Galaxy servers from Home Page for experienced Galaxy users

---

src/build/check-links.mjs

It was always correctly reporting the number of broken links, but it was failing to correctly generate the helpful report of what those were.

Fix linkchecker report -- now it'll actually list broken links and their pages.

---

content/events/gcc2024/training/index.md

backslash at the end of href is acting as close for a tag, and it seems that may be what's causing the broken links.

removing ending backslash, as it's interfering with closing a tag

---

src/assets/styles.scss
src/pages/Index.vue

Drop gradient in Learn section on homepage -- easier to read the text this way (I doubt the previous version would pass a11y validation) and I think it looks nice and clean.

Style adjustment for Learn section of home.

---

src/index.html

It's down and shouldn't be interfering with pageloads but this is, and is why the tests are failing currently.
todo: figure out why that's actually blocking when it shouldn't be, inject into head post-load maybe?

Drop plausible (temporarily?)

---

src/index.html

We will add back incrementally on only certain pages on gridsome app mount.  This is to avoid the 'welcome' and potentially 'bare' pages that are served in iframes (from usegalay.org, etc) from including analytics code.

Drop Google Analytics from base page; 

---

content/home/research.yml
src/pages/Index.vue

With the homepage content refresh the events box was swapped to a predefined static blob instead of dynamically updating, and it was quickly out of date.  This PR adds back dynamic event listing of the three next upcoming events.
Additionally I unpacked some of the content out of research.yml -- it's simply not useful to stuff all these fields in yaml when they are much easier to read, edit, etc., in the vue file.  How would one know what `research4` was anyway, in the contents?
I'm going to follow up and unpack the rest of the unnecessary yaml separately.

Fix upcoming events on homepage.

---

content/events/gcc2024/index.md

This should move the logo to a new line under the text to comply with the rules for spacing around the logo.

Fixed brno city logo position

---

content/events/gcc2024/training/teaching-gtn-tiaas/index.md

It looks like Both Helena's and Saskia's affiliations got grouped together. this minor change removes the incorrect affiliations and fixes a typo with Helena's last name.

fixing affiliation and last name typos

---

src/components/Carousel.vue

Removing the image advertising that Colabfold is 'coming soon'.

Update Carousel.vue to remove "Colabfold Coming Soon"

---

content/events/gcc2024/cofest/index.md
content/events/gcc2024/training/intro-galaxy-dev/index.md

- Add context to the project ideas guidelines/expectations for the Cofest.
- Add prerequisites to the Intro to Dev (Beginner's handbook) training
@bgruening @dannon

Update Cofest page and intro-to-dev training for GCC 2024

---

package.json
src/build/run.mjs
yarn.lock

Uses lodash.kebabcase to handle paths like:
```
news-2024-08-14-GalaxyInResearch/GalaxyInResearch_Jain2024.png
Which should be:
news-2024-08-14-galaxy-in-research/GalaxyInResearch_Jain2024.png
And not the simple lower(), like:
news-2024-08-14-galaxyinresearch/GalaxyInResearch_Jain2024.png
```

Adjust static file staging location handling

---

content/news/2024-09-02-ChatGPT/index.md

added Arash's suggestions on picture names

Newsitem GPT

---

content/belgium/navbar.yml
content/erasmusmc/navbar.yml
content/eu/navbar.yml
content/genouest/navbar.yml
content/ifb/navbar.yml
content/navbar.yml
content/pasteur/navbar.yml
content/projects/brc/index.md

… in primary and subsites w/ standard project grouping, highlighting BRC Analytics as a major galaxy community project.
I had initially included (redundant) content at `/content/projects/brc/index.md` to have a landing page, but for now, as content develops quickly, it makes a lot more more sense to link directly and only have this placeholder with a redirect.
xref https://github.com/galaxyproject/brc-analytics/issues/104

Add brc-analytics link to projects dropdown

---

content/news/2024-11-26-FLUX/index.md

Update the reference to the ChatGPT tool in the FLUX news post to point to the right post.
There seem to be two similar posts:
https://galaxyproject.org/news/2024-09-02-chat-gpt/
https://galaxyproject.org/news/2023-08-14-chat-gpt/

Update ChatGPT tool reference in FLUX news post

---

.github/workflows/publish.yml

Upgrade `publish.yml` to the latest action versions and simplify the caching process in the workflow. Based on [setup-node docs](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data).
Also, this is done as `cache@v1` is [deprecating](https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/).

Update Publish workflow for improved efficiency

---

content/events/gdc2010/index.md
content/gcc/index.md

These resolve to internal links but weren't flagged by the internal link checker because we were using the full external ref or various aliases.  This fixes the links, and makes them internal as well.

GCC / GDC Link Fixes

---

.github/workflows/links-internal.yml
.github/workflows/lint.yml
.github/workflows/main.yml

actions/cache v1 and v2 are being phased out soon, this bumps to v4.  It should be fully backwards compatible, but let's make sure the workflows run.

Update deprecated github actions/cache

---

content/news/2024-12-03-eudat-conference/index.md

Wrote a news post for EUDAT 2024 as mentioned in [this issue](https://github.com/usegalaxy-eu/issues/issues/645).

Added a news page for the participation in EUDAT Conference 2024

---

utils/gtn-import.py

Limit the retrieval of pull requests to only include those that are currently open, improving efficiency and relevance.

Retrieve only open pull requests

---

content/eu/storage/index.md

The article reads well and super clear. But I have a few concerns on the terminology used in unshared storage which led to confusion between storage and quota.
- The unshared storage is not really a separate storage, it is part of regular long-term storage. On the contrary, the short-term, user-owned are real storages. On the storage dashboard, does user see unshared storage as a separate entity?
- Is this statement true? "Data on this storage cannot be used for public datasets"
- Should we add storage of sensitive data as a usecase for unshared storage?
As I see, there 3 quota classes, long-term, short-term and user-owned. There are sharable and unsharable storage (or space) of long-term user quota.

modify EU storage

---

utils/gtn-import.py

Followup for https://github.com/galaxyproject/galaxy-hub/pull/2966.
Sorry, I forgot to remove the old gtn tag assignment that checks the category.

Eliminates gtn tag assignment

---

content/community/sig/index.md
src/assets/styles.scss

As per our previous GCB meetings, I have simplified the SIG index page and updated the cards to make it clearer they are links. Then SiGs can put all their information (and keep it updated) on their required SiG page, rather than on both the index and their SiG page.

Sig page - update index 

---

Makefile

Note that you may have to do `make build` twice for some reason. Afterwhich `make run` works fine, at least on Mint 21.3.

Update Makefile for latest conda and yarn packages

---

content/home/research.yml
cypress/integration/accessibility.spec.js
src/components/Publications.vue
src/pages/Index.vue

Before this is merged, we probably need to clean up publication details a bit on zotero and pick precisely which ones we'll use.
Right now I'm using:
```
{{ item.meta.creatorSummary }}, 
{{ item.data.journalAbbreviation ? item.data.journalAbbreviation : "preprint" }},
{{ item.data.date }}.
```
So, creatorSummary, journalAbbreviation, and date should be carefully added.  We can add more if we want.  It looks like journalAbbreviation isn't always correct or is sometimes missing currently, so we'll need to update those records.
Another option is to just hit crossref for each doi and request a proper citation format, as mentioned before.  This wouldn't be a lot of extra work, but I think we wanted to use this current approach to force zotero to be curated more.
Drops 'New Platforms' box as …

Fetch pubs from zotero on home instead of manual curation

---

gridsome.config.js

@dannon I am hoping to get the full picture of where visitors are clicking (if at all) on three highly visited landing pages (`/usegalaxy/welcome/`, `/bare/eu/usegalaxy/main/`, `/ifb/`) encapsulated in the `usegalaxy.*` top-level domains. However, Plausible's exit-page metrics don't automatically capture outbound links. Instead, Plausible manages them in its Custom Goals section as a separate thing. Is [the commit](https://github.com/galaxyproject/galaxy-hub/commit/81a46c0abed4f7cdb6fde551ce617f2a6882c9d0) in this PR the equivalent of turning on Outbound Links in Plausible's Site Settings (sample screen below)...?

Outbound links metrics for better exit-page analysis

---

content/news/2022-06-27-gcc2022-webinar-mode/index.md
content/news/2023-09-13-Galaxy-Newsletter/index.md
content/news/2023-09-29-tiaas-mgnify/index.md
content/news/2023-12-19-December2023-Newsletter/index.md
content/news/2024-01-26-Galaxy Leaves Twitter/index.md
content/news/2024-03-18-Team-Meeting-Austin2024/index.md
content/news/2024-03-Galaxy-Newsletter-March2024/index.md
content/news/2024-06-21-Brussels/index.md
content/news/2024-11-28-deNBI-all-hands/index.md

Just noticed multiple blog posts using 'author' instead of 'authors'.

Use 'authors' instead of 'author'

---

content/news/2025-04-07-galaxy-job-radar/index.md

without the subsites it is never listed
fixes https://github.com/galaxyproject/galaxy-hub/pull/3065

fix gjr news item

---

src/pages/projects/esg/Events.vue

I noticed two problems at EuroScienceGateway subsite.
1. When I navigated to the events page, there were many events that are not related to ESG directly, however, they are related to the Europe subsite.
2. I can only look at the events for the last 12 months.
I changed the a few things to address both. It seems fine when I build it locally.
Maybe for future: I feel there are meetings and events related to EuroScienceGateway that are available on Europe subsite and we have to find them and add metadata to them.

Updating the event section of the EuroScienceGateway project

---

content/eu/jumbotron.md

@bgruening I noticed that https://galaxyproject.org/eu/ had a link to GCC2024 registration, so I removed it and replaced it with a reg link for GBCC2025.

removing the reg link for GCC2024 and adding GBCC2025

---

content/get-started/new-leads/index.md
content/news/2024-02-04-jupyterlabs/index.md
content/news/2025-04-14/index.md

I modified a few errors that were reported by EuroScienceGateway partners.
Updated the following pages to correct formatting issues:
1. https://galaxyproject.org/news/2024-02-04-jupyterlabs/ -> The logo at the end did not load previously
2. https://galaxyproject.org/news/2025-04-14/ -> Corrected the date metadata from 2024 to 2025
3. Added a redirect for https://galaxyproject.org/get-started/new-leads/ to https://galaxyproject.org/community/

Modified a few pages related to ESG.

---

utils/gtn-import.py

Ensure that slug generation correctly handles URLs by removing any trailing slashes before processing. This is particularly important for external links, which may not follow the same structure as GTN links. Additionally, skip external events that link to Galaxy Hub events to avoid duplication.
This addresses https://github.com/galaxyproject/galaxy-hub/issues/3124.

Fix slug generation in gtn import

---

src/components/pages/News.vue

Ports the tag filter feature from the esg subsite to the main news page, allowing dynamic links like: `https://galaxyproject.org/news/?tag=TIaaS`

Port article tag filtering to main news page

---

.github/workflows/gtn-import.yml

Change the cron schedule to run the GTN news/events workflow.
| **UTC** | **CET** | **PST** |
|---------|---------|---------|
| 00:00   | 02:00   | 17:00   |
| 08:00   | 10:00   | 01:00   |
| 16:00   | 18:00   | 09:00   |

Update cron schedule for GTN news/events workflow

---

src/components/Supporters.vue

I think now the supporters box at the bottom of the page should work better. Previously after this [PR](https://github.com/galaxyproject/galaxy-hub/pull/3139) they could appear extremely large for pages with only 1 or 2 supporters metadata.

Adjusted the width and height of the supporter card at the bottom of the page.

---

.github/workflows/publish.yml

I assume this is not enough/proper. 
This PR is in a naive attempt to fix publish workflow, throwing:
```
error linkinator@6.1.2: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"
error Found incompatible module.
```
xref: https://github.com/galaxyproject/galaxy-hub/actions/runs/15577800186/job/43865985577

update node to 18

---

content/events/2025-admin-training-brno/index.md

@bgruening, @Sch-Da the de.kcd funding was missing at the amin workshop. Is this correct?

added de.kcd as funder to admin workshop

---

content/community/sig/microbial/index.md

Issue here : https://github.com/galaxyproject/galaxy_codex/issues/455
The current link is https://galaxyproject.github.io/galaxy_codex/microgalaxy/ --> 404
New link https://galaxyproject.github.io/galaxy_codex/communities/microgalaxy/resources/ --> works
I think this should work

Update index.md to repair microgalaxy sig broken link

---

content/authnz/config/oidc/index.md

Old content outdated: `config` prefix prepended automatically based on instance configuration.

Update paths in OIDC docs
