- src/styles/styles.less
Classes should be preserved.  Styling can be messed with.
> Added div class styles from old wiki that survived the translation.

- layouts/layout.pug
- src/css/styles.less
Has display issues w/ navbar, just need to bump z-index or give it a custom element.
> Add gitter lobby to site.

- src/GalaxyUpdates/2016_12/index.md
There are some broken internal links in the Events table, but since this is in HTML I'm not sure what's the best way to fix them.
> Fix 2 links

- README.md
This is also testing editing a page directly in GitHub (as mentioned in the readme).
One thing to note, it's near impossible to keep the 80 char wide formatting using GitHub editor (unless I'm missing some feature).
> Add link to live website in README.md

- README.md
It was mentioned that it "would build shortly" during admins chat, would be nice to link in build status.
> Add badge for build status

- src/GalaxyTeam/index.md
Not sure what to do with their pictures.
> Move Carl and Ross to Former Members section

- src/css/styles.less
fixes #101 
**before**
**after**
> improve styling of links and code

- src/config/menu.yaml
- src/iuc/index.md
- src/tools/index.md
- src/toolshed/index.md
- src/toolshed/publish-tool/index.md
> Improve some TS-related pages

- src/public-galaxy-servers/index.md
@nekrut looks like it still generates a toc, is this what you tried?
> Swap back to using yaml frontmatter title for public-galaxy-servers

- layouts/layout.pug
We probably want to revisit this to potentially make it a page-level conditional depending on how expensive our javascript stack turns out to be.  Making it conditional is, of course, more cumbersome to the user, though.
> Include mathjax

- src/iuc/index.md
Hi,
I filled my affiliation on IUC page.
Bérénice
> Affiliation filling on IUC

- src/events/index.md
I guess I don't have commit privileges yet... 
I added a new event that Mo and I are doing in March.
> Added FDA training event Mar 6

- src/events/fda2017/index.md
For FDA-sponsored workshop on Mar 6, 2017.
> Created index.md for FDA 2017

- src/admin/get-galaxy/index.md
No content edited. Just fixes for code formatting, grammar, readability, etc.
> Fixed typos, formatting, and grammar for admin-get-galaxy page.

- src/community/index.md
General fixes for grammar specifically for the GTN, France/French, and Spain/Spanish sections. Clicked all links - appear to be good.
> Grammar fixes

- src/admin/tools/add-tool-tutorial/index.md
- Updated broken links
- Unified tone and tense of tutorial
- Clarified tool definition vs configuration file
- Updated ToC formatting (I think?)
> Updated the add-tool-tutorial page

- src/outreach/index.md
Removed bit about brochures (what year is it?!)
Updated broken image links (thanks to Dannon for migrating the images)
Reworded some paragraphs for clarity/grammar
Replaced html formatting of images with markdown
Added ToC
> Update outreach page

- src/community/index.md
- Replace html image formatting with markdown
- Remove multiple links to the same hub page listed in the same sentence
- Minor clarity/grammar fixes
- Added conda/bioconda as a special interest group
> Update community page

- src/cite-u-like/index.md
- Converted html table to markdown
- Removed redundant links
- Minor grammar/formatting fixes
- Added ToC
- Pruned table of tag links to a subset of (subjectively) interesting ones
> Update cite-u-like page

- src/news/2017-02-release/index.md
> Add in release and committer links

- src/proteomics/index.md
- Corrected use-cases link
- Added twitter link
- Removed LinkBox
> updated proteomics page

- layouts/layout.pug
probably remnant of `make watch`
> remove include of livereload script from every page

- src/teach/computing-platforms/index.md
- Fixed grammar
- Removed redundant links
- Mild reorganization
> updated computing-platforms

- src/css/styles.less
- src/events/index.md
- src/galaxy-updates/2017-03/index.md
@tnabtaf This is a start.
Followup: I looked into swapping *all* tables without a defined class in one pass, but there are a *LOT* of tables and I worry it's a big overreach to do it all at once -- reasonable to update tables as we come across them?
> Table styling swapped to bootstrap striped tables.

- layouts/layout.pug
- layouts/search.pug
- src/config/menu.yaml
- src/search/index.md
galaxyproject.org/search/  - a single channel search.
> Pan-galactic search.

- layouts/layout.pug
in future we might want to have this configurable?
this is the former galaxyproject.org tracking code
> add GA tracking

- src/support/tool-help/index.md
Page could be expanded with graphics showing how the different sections of a tool form are structured.
> Remove linkbox

- layouts/layout.pug
- src/config/menu.yaml
- src/css/styles.less
The "Community" menu was very long compared to the other two, and the 'Teaching' bits seem to make more sense (to me, at least) in an "Education" menu item, combining the previous "Learn" and "Teach" (which got shunted into Community recently).
> Education menu

- src/config/menu.yaml
Change suggested by @nsoranzo, I like it too.
> Swap education and community in menu

- src/public-galaxy-servers/CPTLogo.png
- src/public-galaxy-servers/index.md
Out of date quota information, logo
> Update CPT server info

- partials/Develop/ResourcesTools.html
fixed link under "A somewhat complete description"
> fixed broken link

- src/cloudman/hadoop/index.md
Removed blank space in Markdown
> Removed space in the "See Also" section index.md

- README.md
- layouts/events.pug
- layouts/news.pug
@martenson This should support ToCs on news and events pages when ```autotoc: true``` is set.
> Toc for events news

- layouts/events.pug
@dannon, This works, but it may not be the best way to do this.  I'm trying to have the event image link to the event's URL.
> Modified event layout to have image link to event URL.

- src/admin/config/performance/production-server/index.md
SQLite has excellent support for concurrency, supporting ACID transactions is one of it's best features.
The issue in a production setting is one of performance, not correctness.  In situations where writes (updates, inserts, deletes) are frequent the 'single-writer' paradigm will reduce performance.
> Better explanation of SQLite's issues for prod svc

- src/admin/config/nginxProxy/index.md
The missing links to `Main` and `Test` are added.
> Added missing links.

- src/learn/index.md
- src/tutorials/collections/index.md
- src/tutorials/upload/index.md
- src/tutorials/upload/upload_logic.png
the branch name is a misleading - this is not an NGS, but rather data upload. I will remove data upload section for NGS logistics tutorial in the next PR
> new tutorial on data upload

- src/admin/config/performance/purge-histories-and-datasets/index.md
To run the scripts, it seems that you need to either have installed some packages on your system python, or activate galaxy virtual environment. This might be an interesting note to people trying to run the scripts. 
Also, made some changes to the text formatting.
> Some clarity and formatting

- src/tutorials/pt_gfam/index.md
Sorry I missed this typo in my initial commit!
> Fix typo for PlantTribes tutorial

- src/admin/index.md
- src/admin/ten-simple-steps-galaxy-as-a-service/index.md
ping @hrhotz :)
Please fee free to edit further.
> Ten Simple Rules for Setting up a Galaxy Instance as a Service

- src/public-galaxy-servers/index.md
You can drop this PR if there is an other way to add a public instance :)
> Add the ABiMS Galaxy instance in the public one

- src/admin/config/user-information/index.md
* images are missing
* /src/admin/interface seems to be missing (@martenson do you know if this was on purpose?)
> user information

- src/public-galaxy-servers/index.md
https://github.com/galaxyproject/galaxy-hub/pull/262
Sorry! I thought that the picture resize was done with a CSS
> Update the ABiMS logo

- src/visualization-setup/index.md
Google no longer maintains this code.
> Update bedtools reference

- src/admin/config/performance/scaling/index.md
link to @natefoo admin exercise on how to configure Zerg mode.
> Add a link to the GCC2017 admin training on transparent restart

- src/events/gccbosc2018/organizers/index.md
I haven't been with Trinity for some time now. :)
> Change hlw affiliation to Hosted Graphite.

- src/teach/index.md
- src/teach/survey/index.md
- src/teach/survey/raseq2.png
I created a survey to ask the community what are their need in RNAseq Training material.
> Survey RNAseq for Training Material 

- src/community/index.md
Hi All,
I'm writing doc on how to update the hub and I created this account so I would have a non-privileged account to do stuff from.  So **don't give this account any special privileges!**
However, this is a real pull request that updates text on the Community page.  Please review with the normal protocol.
Thanks,
The non-privileged Dave C
> Added links and fixed image paths to work in GitHub editor.

- src/admin/config/nginx-proxy/index.md
In addition add links to the relevant reports documentation.
> nginx docs: add section to protect the reports app

- build.js
- layouts/public_server_json.pug
- src/public-galaxy-servers/feed.md
Suuuuuuper minimal example of what a public servers JSON feed would look like.  Will refine more in the morning.  (xref a thread w/ @tnabtaf, @erasche, @martenson)
Instead of an exclusion list, we should pick which elements we care to include and use that.  It should also (obviously) generate a .json file and set headers correctly, instead of .html.  This is a good starting point, though.
> Simple public servers json feed.

- src/galaxy-team/index.md
Sorry to see you go @malloryfreeberg!
> Move Mallory to Former Members

- src/galaxy-updates/2017-12/index.md
xref. http://www.triconference.com/Converged-IT-and-the-Cloud/#Day1
It seems that was a copy-paste mistake.
> Fix James's talk title

- README.md
- src/admin/config/tool-dependencies/index.md
- src/admin/data-integration/index.md
- src/admin/tools/data-tables/index.md
- src/splash/metag/index.md
Trying to follow some of the guides today, and found it pretty frustrating. Trying to update as I figure things out
> Fixing some links and wording

- build.js
- layouts/homepage.pug
- layouts/layout.pug
- src/css/styles.less
- src/splash/metag/index.md
- src/splash/planemo/index.md
- src/splash/planemo/planemo-logo.png
- remove gray carousel bg
- fix the carousel controls and indicators, improve styling
- order slides randomly on build
- select and show random one at page load
- improve styling of slides
- minor adjustments to few existing slides
> Homepage carousel improvements

- src/admin/config/nginx-proxy/index.md
See question https://gitter.im/galaxyproject/Lobby?at=5a4cce6e84fb74b940318975
> Adjust note about nginx enabled sites configuration

- src/blog/2018-01-galaxy-r-markdown-tools/index.md
> add Galaxy markdown tools blog entry

- src/events/2017-04-agrocampus-ouest/index.md
In case someone want to directly ask me questions concerning the training ;)
> Add trainer name for APril France RNAseq training ;)

- src/events/gccbosc2018/collaboration/index.md
Dave -- this looks excellent. I added some additional color around why
we moved the collaboration to the end, and also provide pointers to
non-GCC projects. I moved that up the list a bit so folks definitely
know this is not Galaxy specific and we welcome anyone interested in any
open source bioinformatics project.
> Collaborate: non-GCC projects, additional pointers

- src/events/gccbosc2018/location/index.md
Hi Dave, these are the changes to location/index.md (to add information about lunches being included in the event registration) that we discussed in the 2/9 teleconference. Cheers, Steve
> updated with lunch information

- src/events/gccbosc2018/venue/index.md
Added Sellwood as a nearby neighborhood
> Edits to the venue section

- src/events/gccbosc2018/faq/index.md
added requirements for registration and abstract for visa
> added requirements for registration and abstract

- src/splash/metag/index.md
as per the suggestion of one of the referees of the training materials manuscript
ping @nekrut
> Reword title of training slide in carousel

- src/events/gccbosc2018/organizers/index.md
fixed typo in Hilmar's, university -> University
fixed BOSC chair/co-chair designations
> changed Bastian's affiliation

- src/galaxy-updates/2018-04/index.md
> will mirro, not yet in place

- src/galaxy-updates/2018-05/index.md
(you can move or reformat that added section if you want)
Also made a few tweaks to wording.
> added BOSC LBLT deadline

- src/tutorials/g101/index.md
> remove double word

- src/iuc/index.md
See https://github.com/galaxyproject/tools-iuc/issues/1993 .
@bernt-matthias Can you check your details are correct, please?
> Add Matthias to IUC member list

- src/events/2018-europe-dev/index.md
adding preliminary (empty) schedules and confirmed speakers
> Update index.md for European Galaxy Days

- src/admin/get-galaxy/index.md
Header said "exiting" instead of "existing".
> Fix typo in index.md

- src/events/gcc2019/organizers/index.md
updated affiliation of myself in list of GCC2019 organizers to include the myriad of affiliations...
> updated affiliation FC for GCC2019

- src/events/2018-europe-dev/index.md
Hi,
I add the links to my slide decks for the European Galaxy Days.
Bérénice
> EGD: Add links to slides

- src/events/2018-europe-dev/index.md
> GCC talk slides added

- src/news/2018-12-galaxy-update/index.md
> Newsletter: add two more training materials highlights

- src/community/galaxy-admins/meetups/2019-02-21/index.md
- src/community/galaxy-admins/meetups/2019-02-28/index.md
- src/community/galaxy-admins/meetups/index.md
- src/events/2019-02-galaxy-admins/index.md
- src/news/2018-12-galaxy-admins/index.md
Announce call for topics for GalaxyAdmins in 2019.
> Galaxy admins

- src/blog/2019-01-academic-clouds/index.md
Dave, can you merge this block please :)
> adding lifeportal oslo

- src/events/gcc2019/training/index.md
ping @bgruening 
The form is updated in the same way
> Update of the trainings for GCC2019

- src/events/gcc2019/training/index.md
> GCC2019: Update 101 training description

- src/admin/tools/data-managers/testing/index.md
I don't merge this myself to add the question if there are any plans to improve &/ move the data manager docs?
> corrected data manager test command

- src/images/logos/mozilla-science-lab-logo.png
- src/news/2019-03-galaxy-carpentries/index.md
New news item about Gallantries.
> Galaxy carpentries

- src/events/2019-05-gtn/cofests.png
- src/events/2019-05-gtn/index.md
Hi, 
Here are the next GTN events on May
Bérénice
> Add event for next GTN cofest and calls

- .travis.yml
WIP, going to iterate fixing the build here.  We want to pin against the latest LTS node for stability.
> Attempt to use only lts node from travis

- .travis.yml
- Makefile
WIP again, testing locking docker version down in the makefile.
> Lock node docker version in Makefile

- src/events/2019-06-gallantries/index.md
Hi,
This PR adds an event for the Gallantries workshop in June 2019
Bérénice
> Event for Gallantries June 2019 workshop

- src/galaxy-team/index.md
> Update Nuwan affiliation

- layouts/use_index.pug
- package.json
- src/js/index.js
- yarn.lock
Can someone who actually understands JQuery, npm, node, etc take a look at this?
> Update JQuery from 3.3.1 to 3.4.1

- src/use/openminted/OpenMINTED_Tag_Color.png
- src/use/openminted/index.md
OpenMinTeD use-case description
> OpenMinTeD use-case description

- src/support/commercial/index.md
deena bio produced a 500 error
> removes dead link

- layouts/layout.pug
@tnabtaf this is a follow up to our conversation at the team meeting a couple of weeks ago. Let me know what you think.
> Update matshead layout

- src/people/almahmoud/index.md
> Updating almahmoud text

- src/cloud/k8s/eks/index.md
- src/cloud/k8s/index.md
I went through the steps listed in the first implementation by @VJalili and made some small grammatical changes and minor fixes for clarity
> Eks tutorial edits

- src/tutorials/g101/index.md
> Fix a typo in tutorial Galaxy101

- src/admin/tools/data-tables/index.md
This is based on feedback received (https://github.com/galaxyproject/tools-iuc/pull/2655#discussion_r340049857) after using the above suggested code based on this documentation.
> Updated data table object path access method.

- src/admin/config/windows/index.md
These instructions are based on how I set up Galaxy on my laptop during the ELIXIR Biohackaton 2019 for the Windows subsystem for Linux.
> Complete update on how to install Galaxy on a Windows system

- src/use/laniakea-indigo-datacloud/index.md
update issues and main web site link
> upadate links

- src/admin/config/windows/index.md
Still no solution but to the Error: ENOENT but at least a workable solution.
I've been testing this and the initial diagnosis was wrong. What solved the problem was that I ran the run.sh script several times which resolved all the dependencies as it's a random package each time which faills to install properly.
> Diagnosed the Error: ENOENT issue a bit better.

- src/admin/config/access-control/index.md
Replacing all mention of galaxy.ini by galaxy.yml
> Update access control index doc

- src/index.md
So I rewrote some of the bullet points based on the [training material's]https://training.galaxyproject.org/training-material/topics/introduction/slides/introduction.html#4) intro slides to clean up the language a bit.
I removed biomedical since we have so much more and I don't want to give anyone the idea that galaxy isn't for them.
After my chat with @annefou the other month I tried to mention the community focus but I'm not sure if I've done that in a way that's communicating what we want?
@tnabtaf would definitely appreciate your feedback here :)
> More than biomedical

- src/blog/2020-04-integrative-meta-omics/index.md
xref: https://galaxyproject.eu/posts/2020/04/14/integrative-meta-omics/
> add new blog post

- src/authnz/config/oidc/idps/cilogon/cilogon-login-list.png
- src/authnz/config/oidc/idps/cilogon/index.md
Add instructions on how to set up CILogon OIDC login
> CILogon Documentation

- src/usegalaxy/index.md
cc @natefoo @Slugger70 @tnabtaf 
Couldn't find where we did this? Maybe I just forgot for an extended period of time? And I see the list growing in some places and yeah, we need to document the standards we wanted.
> usegalaxy.* stuff

- src/authnz/config/oidc/idps/custos/custos-login-button2.png
- src/authnz/config/oidc/idps/custos/index.md
First pass at Custos documentation. To come: information on how to register a tenant
> First pass at Custos Documentation

- src/authnz/config/oidc/index.md
> fix typo: Custos -> CILogon

- src/tutorials/ngs/index.md
Saw the small typo while looking through tutorials for a dataset
> "tutorual" typo

- src/authnz/use/oidc/index.md
> Fix tiny typo

- src/news/2020-07-galaxy-update/index.md
> Added GW sponsorship to July news.

- src/develop/architecture/index.md
- src/develop/index.md
- src/develop/jsa/index.md
There is a lot of information here but I think it is largely out of date.
> Link out to more updated development documentation.

- src/galaxy-team/index.md
Hey, just noticed the link to my personal site was http, not https!
> Team page: http -> https on nstoler.com.

- layouts/events_index_webinars.pug
- src/events/2019-12-single-cell-ebi/index.md
- src/events/2020-04-elixir-covid-1/index.md
- src/events/2020-05-elixir-covid-2/index.md
- src/events/2020-05-elixir-covid-3/index.md
- src/events/2020-05-elixir-covid-4/index.md
- src/events/2020-05-elixir-covid-5/index.md
- src/events/2020-05-sgci/index.md
- src/events/2020-06-sgci/index.md
- src/events/2020-06-sra/index.md
- src/events/2020-09-niaid/index.md
- src/events/2020-11-abc-webinar/index.md
- src/events/2020-11-du-novo/index.md
- src/events/2020-12-chloroplast/index.md
- src/events/index.md
- src/events/webinars/index.md
Created an events sub-page for webinars only.  And thus the Galaxy Webinar Series is born.
> Created a Webinar events sub-page.

- src/events/2020-11-papercuts/index.md
> Add bioblend to papercuts event

- src/citing-galaxy/CancerMedicine.gif
- src/citing-galaxy/CurrentProtocolsInBioinformaticsCover.gif
- src/citing-galaxy/CurrentProtocolsInMolBioCover.gif
- src/citing-galaxy/GenomeBiologyColver20108.gif
- src/citing-galaxy/GenomeResearchCover200510.gif
- src/citing-galaxy/JAMIACover.gif
- src/citing-galaxy/NatureBiotech201502Cover.gif
- src/citing-galaxy/NatureBiotechnologyCover201211.gif
- src/citing-galaxy/index.md
Dropped emphasis on pubs from US team.  We are global and this page now reflects that better.
@blankenberg **or** @beatrizserrano. Would you mind taking a look at this?  Just want to make sure I am not missing anything obvious.  Thanks.
> Revamp citing-galaxy page.

- src/community/wg/index.md
per request -- let me know if there's a more canonical ordering
> updating cancer informatics wg info in community page

- layouts/layout.pug
> Move Jobs in nav menu from own category to inside Community drop down.

- src/news/galaxy-at-pag2012/index.md
A space in the date value broke it. Now it's fixed.
> Fix invalid date in news/galaxy-at-pag2012/index.md.

- src/community/steering/index.md
xref. https://galaxyproject.org/community/exec/
> Exec is Board

- src/news/2021-03-galaxy-update/index.md
> Newsletter: change institute for 2 winners

- src/events/2021-06-elixir/index.md
@tnabtaf not sure about the `days`, I set it to 11 because this is the total duration of the AHM, but the workshop will take 3 hours...
> add workshop AHM

- src/community/galaxy-admins/future/index.md
- src/community/galaxy-admins/index.md
Discussed on gitter the week starting Monday 3 May
> Point Galaxy-Admins page at Gitter

- layouts/homepage.pug
- src/jxtx/index.md
- src/style/styles.scss
Publishing the @jxtx birthday video.
> James Taylor Birthday Video.

- src/community/steering/index.md
As promised.
Promoted me to emeritus while I was at it :)
> Added committee wg names and leaders

- src/community/steering/index.md
@tnabtaf: Suggested banner for GGSC hub page announcing community input opportunities?
> temporary announcements for GGSC community consultation

- README.md
- content/community/wg/index.md
- content/homepage-pubs.md
- src/components/NavBar.vue
- Update README to say use Yarn 1, not 2
- Added Sam as UI/UX WG co-lead
- added latest pub
- Updated top menu to include governance and coc under community.
> Started making Hub updates in this branch instead of MEtalsmith.

- src/events/2021-12-roscoff-assembly-annotation/index.md
Adding a new (in person!) training in december. It will be in french, but adding it anyway for the record. Feel free to adapt as needed
> Add roscoff december training

- src/events/2021-12-roscoff-assembly-annotation/index.md
Replaying #768 onto the gridhub branch.
> Add roscoff december training (to gridhub branch)

- src/components/NavBar.vue
- src/templates/Article.vue
Needs some more tinkering (see TODO) but it's a start.
> Add GitHub edit to gridhub branch

- content/news/2021-09-galaxy-update/500-subscribers.png
- content/news/2021-09-galaxy-update/TIaaS-flyer.png
- content/news/2021-09-galaxy-update/index.md
- content/news/2021-09-galaxy-update/misconceptions.png
- content/news/2021-09-galaxy-update/training-sars-cov-2-worldstats.png
- content/news/2021-09-galaxy-update/use-case-example.png
First version of the newsletter.
> Add first version of the newsletter

- content/events/2021-10-hybrid-assembly/index.md
- content/news/2021-09-eu-annual-reports/index.md
> Gridhub 2021 09 13 misc update

- content/galaxy-team/index.md
Fix markdown handling in team page -- still need to fix a bunch of images and other stuff
> Fix `galaxy-team` page.

- src/pages/Index.vue
Computeds should never modify local state here (no side effects)
> Fix jobs listing on homepage

- content/careers/2020-10-schatz-srpa/index.md
- content/events/2021-09-qcif-rna-seq/index.md
- content/events/2021-12-roscoff-assembly-annotation/index.md
- Hopkins job closed
- QCIF event added
- Updated date for IFREMER event
> Miasc updates

- src/components/ArticleHeader.vue
- src/utils.js
Apparently I wrote a `startswith()` function before I realized `String.prototype.startsWith()` exists!
> Remove redundant `startswith()` util.

- gridsome.config.js
- gridsome.server.js
- src/utils.js
Didn't realize you could `require()` a json directly!
Much simpler.
> Simplify importing config.json - import it directly.

- gridsome.server.js
- package.json
- src/components/ArticleHeader.vue
- src/templates/Platform.vue
- src/utils.js
- yarn.lock
Misc cleanup and refactoring in some of the utils; trying to cut down on the custom code we have here.
> Utils cleanup

- src/build/fix-links.mjs
- src/build/mdfixer.mjs
- src/build/partition-content.mjs
- src/build/preprocess.mjs
- src/build/run.mjs
- src/paths.js
- src/utils.js
Biggest item: move `PathInfo` into its own module `paths.js`.
Also:
- rearrange order of functions in `utils.js` a little
- replace some instances of `.indexOf(X) === 0` with `.startsWith(X)`
- remove `describeObject()`
> More utils cleanup and rearranging.

- content/jumbotron.md
@NickSto and @dannon: What do you think? Is this the right way, or not, to do this?
> Adding images on links on home page to GCC2021 Videos.

- content/news/2021-09-galaxy-update/index.md
Mostly adding the `.trim-p` class to remove padding around Markdown elements.
> Improve September newsletter display & Gridhub compatibility.

- .github/workflows/links.yml
We don't actually want this to run on pull-request, we want it as a nightly cron job.  Just running it this way to test and make sure it's going to do what we want.
Right now it's just looking at a specific collection of the 15 most visited pages, because the full site has something like 30k links.
> Link checking CI

- content/news/2019-07-galaxy-update/index.md
- content/news/2021-07-galaxy-update/index.md
- content/news/2021-09-galaxy-update/index.md
- content/tutorials/nt_rnaseq/index.md
Some benefit already from @dannon's link checker!
> Fix some internal links.

- cypress/integration/main.spec.js
- src/components/NavBar.vue
NavBar, Bootstrap JS, redirects, static page rendering.
> Add several new tests

- content/people/dave-clements/index.md
> Testing new push restrictions.

- content/user-defined-toolbox-filters/index.md
Remove the invalid link pointed out by #881.
Convert HTML links/imgs to Markdown.
> Fix #881 and convert some HTML to Markdown.

- src/layouts/Default.vue
Not sure why, but the footer got knocked out of its centered alignment.
Also, improve the vertical padding above and below it a little.
> Fix footer placement.

- content/news/2021-11-galaxy-update/index.md
Tthis fixes the latest newsletter page breaking on initial load -- we need a better way to enforce valid html in these.
> Fix dangling div that broke newsletter initial render.

- .github/workflows/main.yml
- content/community/devroundtable/index.md
- content/news/2021-11-galaxy-update/index.md
- src/build/check-links.mjs
This updates our github workflows to run (internal only) link checking and jest unit tests on PR submission.  This caught several freshly broken links which are also fixed here.
> Run tests (link checking and jest) on PR submission.  Fix serveral (new) busted links.

- content/admin/config/windows/index.md
- content/events/2020-11-biohackathon-europe/index.md
- content/events/gcc2013/bof/index.md
- content/events/gcc2013/bof/linkbox.md
- content/events/gcc2013/header.md
- content/events/gcc2013/program/index.md
- content/events/gcc2013/training-day/index.md
- content/events/gcc2014/linkbox.md
- content/events/meetups/p-s-u/index.md
- content/events/meetups/psu/2015-03/index.md
Checked all places where `~~strikethrough~~` syntax is used, fixing broken instances and porting some pages on the way.
This fixes #1005.
> Fixed more page compatibility issues, plus broken ~~strikethroughs~~.

- content/homepage-pubs.md
- content/use/laniakea/index.md
And it's a tour de force of applying Galaxy on Cloud infrastructures.
> Added new paper for Laniakea.

- src/build/fix-links.mjs
- src/build/fix-links.test.mjs
- src/build/mdfixer.mjs
Tests for this function have been a long time coming.
This also removes the use of a global to affect its functioning.
P.S. This should help if we have to change this function to support subsites.
> Added some tests for fixImageLink() in fix-links.mjs

- content/careers/2021-10-recetox-scientific-sw-dev/index.md
- content/events/2021-11-papercuts/index.md
- content/events/2021-12-vib-cloud/index.md
- Added VIB cloud event
- Fixed application date on RECETOX opening
- Updated Papercuts
> This morning's updates

- content/events/2022-04-sib-introduction/index.md
- content/news/2021-11-gtn-video-lib/index.md
- Added GTN Video library news item.
- Added SIB training in April
> Tuesday AM updates

- content/iuc/index.md
Tables used an incompatible format for CommonMark/Hub2.
> Fix tables in /iuc/.

- content/iuc/index.md
Per galaxyproject/tools-iuc#4208
@gallardoalba welcome, and please double-check the info is correct
> Add Cristóbal Gallardo to /iuc/.

- content/blog/2021-11-RShiny_GxIT/index.md
Some minor changes and fixes about the shape of the article
> Minor review

- content/covid19/footer.md
- content/covid19/genomics/no-more-business-as-usual/index.md
- content/covid19/index.md
The logo footer is reused and belongs in an Insert.
> Move COVID-19 project logos into a reusable Insert.

- content/people/dannon-baker/index.md
- package.json
- src/build/partition-content.mjs
- src/components/VegaEmbed.vue
- src/main.js
- yarn.lock
Super simple vega wrapper component for @nekrut.
Adds a new component that can be used like this from any markdown:
```
<vega-embed spec="https://raw.githubusercontent.com/vega/vega/master/docs/examples/bar-chart.vg.json"/>
```
And it shows up something like this:
Kept it as simple as possible for this example, but we can map more attributes like styling/rendering options, whatever, as necessary.
> Vega component

- content/events/gcc2022/conduct/index.md
- content/events/gcc2022/header.md
- content/events/gcc2022/schedule/index.md
I don't know about that guy...
> Fix evil HTML introduced by former member of the team

- content/news/footer.md
Old URL went to 404 missing page
> Fixed URL pointing to GitHub for adding a news items

- content/news/2021-07-galaxy-update/index.md
Cleaning up some old branches and this one is a good fix.
> Typo fix in link in July news.

- content/events/2022-01-admin-training/index.md
@beatrizserrano is this right?
> Add redirect

- src/components/HomeProfile.vue
The max-width being in % interacted badly with the changing number of columns in the b-row.
Fixes #1133.
> Fix homepage responsiveness issue with the HomeProfiles.

- src/components/HomeProfile.vue
- src/pages/Index.vue
> Fix HomeProfile top/bottom spacing.  

- content/blog/2021-12-12-outreachy-meet-chinonye/index.md
I really hope I did this correctly...I'll appreciate corrections if I did it wrongly:(
Thank you!
> Add Outreachy blog post

- content/usegalaxy/welcome/main.md
They available in the Galaxy help menu for the curious, but this links them near other relevant text in the welcome as well.
> Link Terms directly from usegalaxy welcome

- content/search/main.md
- src/pages/Search.vue
When there's no query, show a box indicating that you should enter something to search for.
~Following up making this reactive, but this was a quick 5-minute fix.~   Done.
Will fix #1168
> Search tweaks

- content/usegalaxy/welcome/main.md
Turns out it's a good idea to actually view your changes before submitting them. Also I think the TACC logo should be centered but it's not?
xref #1177
> Fixes to welcome page

- content/community/wg/index.md
Still a few questions on here, but this page is out of date and does not reflect actual organization. 
I figured I'd give it a quick once over.
> updating working groups page to reflect reorganization

- content/blog/2022-01-03-Galaxy-Mentor-Network/index.md
I wrote a blog from Outreachy prompts describing my project; Galaxy Mentor Project
> New blog post

- content/events/gmn-launch/index.md
Updating the timeanddate link  to correct dates/times and adding Zoom links for GMN lauch events
> adding zoom links for events and updating timeanddate link

- package.json
Add shortcut for doing the preprocessing only.
> Add preprocess command to package.json.

- content/tools/requirements/index.md
By popular demand (#1167, galaxyproject/galaxy#13378).
CC @beatrizserrano
> Restore /tools/requirements/ page.

- content/community/steering/index.md
@fubar2 please feel free to edit as you like and merge! :)
> Update the GGSC page

- gridsome.config.js
- gridsome.server.js
- package.json
- yarn.lock
First pass at generating and publishing an events.ics.  This should get it up there and we can iterate on details.
> Calendar feed

- content/events/2017-10-hacktoberfest/index.md
- content/events/2021-02-mass-spec/index.md
- gridsome.server.js
- src/build/partition-content.mjs
- src/build/preprocess.mjs
Adds url and duration attributes, minor fixes.
> Calendar feed updates

- content/visualizations-registry/code/index.md
- content/visualizations-registry/configuration/index.md
- content/visualizations-registry/cookbook/index.md
- content/visualizations-registry/index.md
@NickSto have I done this right? Or left? ;) I am not sure if I needed to add the redirects to the subfolders too (code, configuration, cookbook).
> Add redirects to visualization-registry

- content/belgium/news/main.md
- content/elixir-it/news/main.md
- content/erasmusmc/news/main.md
- content/eu/news/main.md
- content/freiburg/news/main.md
- content/genouest/news/main.md
- content/ifb/news/main.md
- content/pasteur/news/main.md
- content/us/news/main.md
- gridsome.server.js
- src/components/pages/News.vue
Uses same technique as #1269 but now adds a News page.
> Add a News page for all subsites.

- content/community/index.md
Hi @beatrizserrano 
AS discussed, I added Galalxy ML here.
Thanks!
> Added Galaxy ML to communities of practice table

- content/careers/2022-02-recetox-scientific-sw-dev/index.md
this is continuous recruitment
> remove close date from job add

- content/support/dataset-icons/index.md
I have changed the content of the FAQ in the Hub with the link in the GTN.
> updated dataset-icons in Hub

- content/support/how-jobs-execute/index.md
I have changed the content of the FAQ in the Hub with the link in the GTN.
> Updated Job states in Hub

- content/community/coc/index.md
Today we had the first meeting of the CoC Committee after the CoC was renewed. This PR reflects the changes agreed there:
- Reports made in bad faith are now rephrased.
- Added information of the roles of the members in the Galaxy governance to facilitate reporting.
- I took the liberty to replace the years in the project by the year when we joined it. That will save us from updating the number every year :)
> Updates to the CoC agreed on today's meeting

- content/events/gcc2022/abstracts/index.md
- content/events/gcc2022/index.md
- content/events/gcc2022/key-dates/index.md
- content/events/gcc2022/register/index.md
Don't merge until April 13, 2022.
> GCC2022 updates

- config.json
- gridsome.server.js
- src/components/pages/TaggedEvents.vue
Now you can create a page like `/events/webinars/` or `/community/devroundtable/` just by adding a line in `config.json`!
Implements #1293.
> Move taggedEventsPages definition to config.json.

- content/support/download-data/index.md
Removing the FAQ incomplete dataset download done by @beachyesh and I.
> Removing FAQ - Incomplete dataset download

- content/support/download-data/index.md
Removing the FAQ "Dataset not downloading at all" done by @Nurzhamalyrys and I.
> Removing FAQ - Dataset not downloading at all

- content/support/sort-your-inputs/index.md
Through this Pull Request, I'm updating the content of [Sort your Inputs](https://galaxyproject.org/support/sort-your-inputs/) in the Hub with that of [Sorting Inputs](https://training.galaxyproject.org/training-material/faqs/galaxy/tools_sorting.html) in the GTN.
Kindly suggest any improvements or amendments.
> Updated Sorting_Inputs

- content/support/tabular/index.md
> Removing FAQ Format Help for Tabular/BED/Interval Datasets 

- content/support/metadata/index.md
Replacing the content with GTN FAQ
> Removing FAQ  How do I find, adjust, and/or correct metadata?

- content/support/missing-history/index.md
Through this Pull Request, I'm updating the content of [Missing history](https://galaxyproject.org/support/missing-history/) in the Hub with that of [Finding and working with "Histories shared with me"](https://training.galaxyproject.org/training-material/faqs/galaxy/histories_shared.html) in the GTN.
Kindly suggest any improvements or amendments.
> Updated Missing_History

- content/support/finding-tools/index.md
I have changed the content of the FAQ in the Hub with the link in the GTN.
> Updated finding tools in Hub

- content/support/account-quotas/index.md
Hi! 
I am removing FAQ Quota Usage.
> Removing FAQ Quota Usage 

- content/learn/custom-genomes/index.md
Hi! 
I am removing FAQ Custom Reference Genome
> Removing FAQ Custom Reference Genome

- content/support/account-quotas/index.md
Hi! 
I am removing FAQ Purging Datasets.
> Removing FAQ Purging Datasets

- content/events/2022-03-genome-assembly/index.md
- content/events/2022-04-26-impact-data/index.md
Not sure if I've been very consistent @NickSto
> Tag events for member sites (2021-2022)

- content/events/cofests/papercuts/main.md
Made some changes to papercut event, based on rebranding efforts.
> Update papercuts events

- content/main.md
- src/pages/Index.vue
The "Get Started" button on the homepage is static content that doesn't need to be in the .vue file.
> Move homepage button from Index.vue to main.md.

- content/news/2022-04-20-towards-sustainable-storage/index.md
- content/news/2022-04-24-tool-update/index.md
A few more test imports, this time of news posts.
> Add a couple news posts from .eu

- gridsome.config.js
This is also a test PR to check what's happening with the build tests in #1300.
> Tweak how plugin path globs are composed to be more clear.

- content/belgium/events/archive/main.md
- content/belgium/events/main.md
- content/elixir-it/events/archive/main.md
- content/elixir-it/events/main.md
- content/erasmusmc/events/archive/main.md
- content/erasmusmc/events/main.md
- content/eu/events/archive/main.md
- content/eu/events/main.md
- content/events/archive/main.md
- content/events/main.md
- content/freiburg/events/archive/main.md
- content/freiburg/events/main.md
- content/genouest/events/archive/main.md
- content/genouest/events/main.md
- content/ifb/events/archive/main.md
- content/ifb/events/main.md
- content/pasteur/events/archive/main.md
- content/pasteur/events/main.md
- content/us/events/archive/main.md
- content/us/events/main.md
- gridsome.server.js
- src/components/pages/EventsArchive.vue
Also, tweak the text on existing events pages.
> Add an events archive page for every subsite.

- content/support/account/index.md
- Removed Registering for a Galaxy account
- Removed Updating account preferences
> Removing FAQs in Registering Accounts

- content/support/account-quotas/index.md
- Removed Find all Histories and purge (aka permanently delete) those not needed
- Removed How can I reduce quota usage while still retaining prior work (data, tools, methods)
> Removing FAQs in Account Quotas

- content/support/loading-data/index.md
- Removed Get Data: Upload
- Removed Get Data: EBI-SRA
> Removing FAQs in Loading Data

- content/learn/custom-genomes/index.md
Hi! 
I am removing FAQ Sorting and Troubleshooting Custom Genome.
> Removing FAQ Sorting and Troubleshooting Custom Genome

- content/learn/managing-datasets/index.md
I have updated the content of [Managing datasets](https://galaxyproject.org/learn/managing-datasets/).
Kindly have a look at it, and suggest any improvements or amendments.
> [FAQ] Updated Managing datasets

- package.json
- yarn.lock
Added benefit, the image processing step should be about twice as fast.  42 seconds to 19 on my machine.
> Force more modern sharp for m1 mac compatibility

- content/events/gcc2022/schedule/index.md
It was bothering me that the cards got squeezed unnecessarily like that.
> Make GCC2022 events summary cards a little less squished.

- content/bare/usegalaxy-eu/notices.md
- content/footers/eu.md
- Correct a bit of repeated text.
- Better match the heading style of the Ukraine banner.
- Update link to the (now working) RSS feed
- For now, keep all other links to .eu until we replicate them here.
> Fix small errors and tweak details in the usegalaxy.eu middle pane.

- content/projects/mpxv/index.md
@nekrut Fixing mostly my own wrong PR suggestions here.
> Fix typos and description of WorkflowHub WF import

- content/bare/usegalaxy-eu/notices.md
- content/usegalaxy/welcome/main.md
This PR suggests to change the alert background color from `danger` to the color of the flag of Ukraine since it is not an error message (see: https://en.wikipedia.org/wiki/Flag_of_Ukraine).
> Change alert background color to national flag color

- content/community/arabic/index.md
- content/community/devroundtable/main.md
- content/get-started/index.md
I noticed a few mistakes causing broken links or broken Markdown/HTML rendering. While I was there I also maked some non-functional tweaks to the style of some links.
> Fix some small mistakes and style issues in a few pages.

- content/bare/usegalaxy-eu/metabolomics/index.md
Complete except the carousel content.
> Add metabolomics.usegalaxy.eu's middle pane

- content/bare/usegalaxy-eu/main/index.md
- src/pages/bare/eu/latest/Events.vue
- src/pages/bare/eu/latest/News.vue
And replace /bare/eu/latest/ with them.
> Make widgets for News and Events.

- content/bare/eu/usegalaxy/main/jumbotron.md
> Update usegalaxy.eu middle pane jumbotron image

- content/careers/2022-07-ou-phd/index.md
Adding a career opportunity for a PhD project in statistics
> OU PhD opportunity

- content/people/john-davis/index.md
Markdown fix for broken image noted in #1558
> Fix profile image on /people/john-davis/

- content/blog/2022-07-25_Galaxy_Climate_Project_Introduction_Blog_2/index.md
Thanks for this nice article :)
@ all authors: Soumya Jha, Anne Fouilloux and Jean Iaquinta
> Remove redundant paragraph

- src/components/HomeCard.vue
- src/components/HomeProfile.vue
- src/components/ItemListBrief.vue
- src/components/pages/SubsiteHome.vue
- src/pages/Index.vue
- src/pages/bare/eu/latest/Events.vue
This gives the homecards (the panels on the front page) an overdue due redesign.
I basically ripped off the look of the cards on the .eu homepage because they look way better.
Feedback is welcome!
> Redesign Homecards: light theme

- config.json
- gridsome.server.js
- src/components/Gitter.vue
- src/components/NavBar.vue
- src/layouts/Default.vue
- src/lib/site.js
- src/lib/utils.js
- src/templates/Platform.vue
This designates the default subsite by just storing its name in a `default` key to the `subsites` object in `config.json`.
This makes retrieving it as simple as `CONFIG.subsites.default`.
> Simplify finding the default subsite.

- content/events/2022-10-EGD/EGD/index.md
Once the page looks good, we can link it from the main page
> adding tentative agenda for EGD Oct 4 and 5

- .github/workflows/publish.yml
> Scheduled build and publish every night at 2330

- content/events/2022-09-small-scale/index.md
> create index.md for next small scale meeting

- content/news/2022-08-galaxy-release-22-05/index.md
It took some time and energy to make the release notes and all of the recordings (which we credit in the full release notes) like we credit who tested the release or made specific improvements, if it's being copied wholesale from the one I wrote, maybe nice to record that as well? (feel free to reject, maybe it's just my ego talking).
This seems to be a free text field afaict?
> Adding authorship to release announcements

- content/events/2022-10-egd/index.md
> Update the COVID policy for the EGD

- content/support/account-quotas/index.md
- content/support/account/index.md
- content/support/tool-error/index.md
Goes together with https://github.com/galaxyproject/training-material/pull/3476
cc @shiltemann
> Fix broken links FAQs

- content/events/2022-11-23-bgu/index.md
> Add new event Israel

- content/authnz/config/oidc/idps/custos/index.md
The Custos service address changed recently, and the urls on the Custos configuration setup were outdated.
Similarly, several changes have been made here: https://github.com/galaxyproject/galaxy-hub/pull/1688
> Update Custos config - Custos url change

- .gitmodules
- utils/port-eu-post.py
This is a script I've been using to help port content from .eu. It automates most, but not everything. Posts still can end up broken and need manual review.
Note: This adds a git submodule, since the script uses a module from [this repo](https://github.com/NickSto/utillib) to parse the graymatter.
> Add helper script for porting .eu content

- LICENSE.md
- README.md
MIT for the platform and code, CC BY for the contents.
xref #1664
> Add licenses

- Makefile
- environment.yml
Given a conda environment a simple:
```
make install
make run
```
will get you started. The ugly openssl hack that I needed is included.
> add initial Makefile with install and run targets

- content/news/2022-11-01-openssl-cve/index.md
Wait to merge until galaxyproject/galaxy#14904 is merged or else it's a lie. :smile:
> Add news item covering the impact of the CVE-2022-3602 OpenSSL vulnernerability announced today

- .github/workflows/optimize-images.yml
... from the default 80% quality to 90% to see if this prevents recompression issues seen in recent site-wide compression passes.
> Change webp compression 

- src/layouts/ESG.vue
- src/pages/projects/esg/Events.vue
- src/pages/projects/esg/Index.vue
- src/pages/projects/esg/News.vue
Followup for #1727
Fixes malformed tags and the solo view
> Several fixes for ESG

- content/projects/esg/events.md
- content/projects/esg/main.md
- content/projects/esg/news.md
- content/projects/esg/section_1.md
- content/projects/esg/work_packages.yml
- src/layouts/ESG.vue
Euro Science Gateway -> EuroScienceGateway
> ESG website: Fix typos, some links

- content/news/2022-11-05-EuroScienceGateway/index.md
- content/news/2022-11-06-EuroScienceGateway-Kickoff-Meeting/index.md
- content/news/2022-11-24-ESG-WP1/index.md
This is an example PR that adds 3 blog posts to the ESG website.
> add 3 initial blog posts

- content/news/2022-11-30-Slow-Storage-EU/index.md
I am not sure about the labels yes (my first contribution).
> Slow Storage on EU

- content/news/2022-11-24-ESG-WP5/index.md
This is an introduction for the WP5 goals and activities.
> WP5 introduction

- content/blog/2022-12-02-CoC-EoY-Update-2022/index.md
Blog Post  -- Annual updatefrom CoC Committee
> added blog post with update from CoC members

- content/careers/2022-10-genouest/index.md
Still looking for candidates for this one + a new offer
> Update genouest offers

- content/news/2022-12-08-esg-wp4/index.md
Introduction to ESG WP4.
@enolfc please review.
> ESG WP4 introduction

- config.json
- content/bare/eu/usegalaxy/main/index.md
- src/components/Snowflakes.vue
- src/layouts/Default.vue
- src/pages/usegalaxy/Welcome.vue
Defaults to 60 seconds on, then they go away.
Drops global config -- yagni.
> Refactor snowflakes to component, add to welcome,  add duration

- src/components/Snowflakes.vue
> No snowflakes if prefers-reduced-motion

- content/events/gcc2019/header.md
- content/events/gcc2019/sponsors/index.md
> Cleaned up rendering in GCC2019 header and sponsor page.

- config.json
- content/hub/global/index.md
- gridsome.server.js
- src/components/NavBar.vue
> Ghost sites

- gridsome.server.js
> Fix events feed overwriting/merging with the use feed

- content/projects/vgp/workflows/index.md
Added a new section showing various combinatioins of workflow runs and corresponding results
> adding results of workflow runs

- content/events/2023-03-30-galaxy-metabolomics-community-call/index.md
Added information regarding next galaxy metabolomics community call in march based on a Galaxy community call template
> add next galaxy metabolomics community call

- content/news/2022-10-11_tool-form-improvements/index.md
Semin automatically generated.
> News PR for 14549

- content/news/2023-02-12-lapsgrid-nlp-survey/index.md
Fix dates for Nancy's survey news item - were from 2 months back so sorted off the main page :(
> Old, wrong dates fixed

- content/news/2023-02-05-how-tools-are-maintained/index.md
> add tools post

- .github/workflows/main.yml
(maybe ubuntu-latest bumped default node version, causing this?)
Related to https://github.com/galaxyproject/galaxy-hub/pull/1777
> Test fixing CI

- content/news/2023-03-08-gmn-reset/index.md
> Add news about GMN reset

- content/events/2023-admin-training/index.md
Adds GAT 2023 schedule link and a :new: emoji to the schedule section to highlight it for the users.
> Add GAT 2023 schedule link

- CONTRIBUTING.md
Was using this as a reference and noticed some links and metadata tags were out of date. 
Needs review of `location` tage and to define `tags` and `subsites` tags.
> Update events metadata info in CONTRIBUTING.md

- content/bare/eu/usegalaxy/notices.md
Lets see if an empty line is all it takes.
> Try to fix notice heading

- content/events/gcc2023/schedule/index.md
Updates to GCC2023 Training Schedule
> Updating GCC2023 Training Schedule

- content/bare/eu/usegalaxy/notices.md
Ukraine note will be added back after the switch is over.
The background colour  should look like this:
> Tpv switch note

- content/bare/eu/usegalaxy/notices.md
Switch back to the Ukraine notice
> Tpv switch over

- content/news/2023-01-03-paper-rapp-stat3-il6/index.md
One out of initially three submitted news articles out of PR #1931 (which thus could be rejected/deleted)
> Created news article for Paper Rapp et al. on STAT3 signaling

- content/events/gcc2023/index.md
> fix gcc2023 index button link for program

- content/news/2023-05-06-ABPHM/index.md
Hinxton ABPHM conference Blog Post
> Hinxtonconference Blog Post

- content/events/gcc2023/fellowships/index.md
- content/events/gcc2023/schedule/index.md
Adding Training Schedule to GCC Schedule & striking out past deadline
> Updates to gcc sched

- .gitpod.yml
Enable gitpod configuration.
Allows editing the hub and creating PRs without any local install at all:
> Add gitpod configuration

- content/news/2023-06-06-eu-maintenance/index.md
Ask users to clear their browser's cache if usegalaxy.eu is still not working
>  Maintenance Announcement EU (clear cache)

- content/bare/eu/usegalaxy/notices.md
This is a draft to be marked as ready for review when the necessary PRs for closing [#412 on the issues repo](https://github.com/usegalaxy-eu/issues/issues/412) get merged. At the moment it can be ignored.
----
Temporarily replaces the Ukraine banner.
> Add banner warning of potential disruption of uploads

- content/bare/eu/usegalaxy/notices.md
Reverts galaxyproject/galaxy-hub#2001.
**DO NOT MERGE** until [usegalaxy-eu/infrastructure-playbook#806](https://github.com/usegalaxy-eu/infrastructure-playbook/pull/806) has been merged.
> Remove banner warning of potential disruption of uploads

- content/events/gcc2023/cofest/index.md
Add link to project tracking spreadsheet
> Cofest update

- content/news/2021-03-01-gat/index.md
- content/news/2021-03-16-slides_to_videos/index.md
- content/news/2021-03-17-galaxy_release/index.md
- content/news/2021-03-17-smorgasbord_report/index.md
- content/news/2021-03-18-gcc2021-virtual-edition/index.md
- content/news/2021-03-18-gtn_cofest_may/index.md
- content/news/2021-03-18-tutorial_imaging_cell_profiler/index.md
- content/news/2021-03-24-faqs/index.md
- content/news/2021-03-24-tutorial_assembly_mrsa/index.md
- content/news/2021-03-30-tutorial_scrna_plant/index.md
- content/news/2021-04-06-new-video-player/index.md
- content/news/2021-04-10-tutorial_plant_transcriptomics/index.md
- content/news/2021-09-24-jupyter/index.md
- content/news/2021-09-29-survey/index.md
- content/news/2021-10-12-speed/index.md
- content/news/2021-11-10-api/index.md
- content/news/2022-05-20-schema/index.md
- content/news/2022-06-02-workflow-reports-tutorial/index.md
- content/news/2022-09-11-data-manipulation-tutorial/index.md
- content/news/2022-11-18-singlecell/index.md
- content/news/2022-11-29-deconvolution/index.md
- content/news/2023-01-23-new-covid19-topic/index.md
- content/news/2023-01-24-prometheus/index.md
- content/news/2023-01-26-pathogen-detection-tutorial/index.md
- content/news/2023-02-02-black-history-month/index.md
- content/news/2023-02-08-top-tools/index.md
- content/news/2023-03-21-galaxy-trainer-directory/index.md
- content/news/2023-04-13-learning-pathways/index.md
Publish old news from the Galaxy Training Network that are not covered by the automation from #2068 [as requested](https://github.com/galaxyproject/galaxy-hub/pull/2069#issuecomment-1624905504).
Follow up of #2065.
> Publish old news from the Galaxy Training Network

- content/community/wg/index.md
Update Systems WG leadership, merge Workflows and Tools WGs
> Update working groups

- .gitignore
- gridsome.server.js
> Add JSON news feed

- content/community/czech/index.md
Added reference to EIRENE-CZ for Galaxy developments within the Czech Republic.
> Update Czech regional description

- content/events/2023-09-04-biont-workshop/index.md
Added a BioNT Workshop event where we will teach 5 half days of Galaxy using the GTN.
> added biont workshop event

- content/events/2023-09-04-biont-workshop/index.md
For the RNA-seq BioNT workshop change the subsites to all instead of all-eu.
> updated subsites to all

- content/events/2023-10-egd/index.md
Additions on registration deadlines, community contributions, detailed schedule release, links, contacts, ... typos, formatting.
> Update on EGD2023 events page

- content/bare/eu/usegalaxy/notices.md
I think we can remove the banner now.
---
Reverts galaxyproject/galaxy-hub#2130
> Revert "Galaxy 23.1 upgrade banner"

- content/bare/eu/usegalaxy/notices.md
Reverts galaxyproject/galaxy-hub#2149
> Revert "add EU 'minor disruption in service' notice"

- content/events/2023-09-12-MAdLand/index.md
Hello, 
I have created an MAdLand event. Please review & Merge. 
Thanks, 
Deepti Varshney
> MAdLand event

- content/events/2023-09-12-MAdLand/index.md
@bgruening @Deeptivarshney added a bit more info to the madland event in the hub. Feel free to edit as you see fit of course!
> Add more MAdland meeting info

- content/news/2023-09-13-Galaxy-Newsletter/index.md
News post for the September 2023 Galaxy Newsletter
> Galaxy Newsletter September 2023

- content/events/2023-09-06/index.md
Following suggestion of @hrhotz . Note @bgruening too.
> EuroScienceGateway at Swiss SKA days 2023

- content/news/2023-08-15-GCC2023-Meeting-Report/index.md
- content/news/2023-09-13-Galaxy-Newsletter/index.md
Also standardized case of frontmatter keys.
> Fix subsite specification so newsletters display.

- content/news/2023-09-13-Galaxy-Newsletter/index.md
Adding subsites
Checked and cleared all links
> Galaxy Newsletter September 2023 - Updated

- content/news/2023-09-07-esg-wp5-astronomy-archives/index.md
Some formatting patch is needed to https://github.com/galaxyproject/galaxy-hub/pull/2174 
Does this makes sense @bgruening ?
> Formating patch to Astronomical Data Archives (ESG WP5)

- content/events/2023-10-egd/egd/index.md
Four talks and four BoF added for publishing
> Egd2023 update schedule

- content/events/2023-10-egd/egd/index.md
- content/events/2023-10-egd/esg/index.md
- content/events/2023-10-egd/index.md
Several edits as discussed in the chat - still things to be done, but at least a step...
> Egd2023 update schedule incl esg

- content/events/2023-10-egd/esg/index.md
linked talks, minutes and updated texts in the European Galaxy Days sub-page
> ESG GA 2023 - aftermath

- content/news/2023-10-31-esg-byoc-im/index.md
Pending: upload video recording and add the link below.
> News item for pulsar deployment with Infrastructure Manager

- content/news/2023-08-21-usegalaxy-eu-upgrade-23-1/index.md
Retroactive blog post to be included in reports.
> Add blog post on the Galaxy Europe upgrade to Galaxy 23.1

- content/news/2023-11-08-esg-psa/index.md
A short news item on the PSA release with ESG contributions
> A news item on the psa release

- src/index.html
> Update to GA4

- content/news/2023-06-26-elixir-ahm/index.md
Added F1000 reference to ELIXIR's official meeting report (following comment https://github.com/usegalaxy-eu/website/issues/1065#issuecomment-1725034177)
> News on ELIXIR AHM 2023: Update index.md

- content/news/2023-11-16-uni-freiburg-new-rdm-policy/index.md
University of Freiburg with a new policy on Research Data Management
> News on UFR RDM policy update

- content/projects/cop_template
It begins! Making a template page for our communities of practice to make their lives easier
> Create cop_template - WIP

- content/use/usegalaxy-fr/index.md
- content/usegalaxy/index.md
And add usegalaxy.fr since they meet the requirements.
> Update the usegalaxy membership rules based on gcc discussion

- content/tutorials/collections/index.md
I have been having some issues with getting this redirect link to work. If this try is unsuccessful, I would appreciate any assistance!
> Trying to fix redirect links

- content/events/2024-02-26-hackathon-image-analysis-in-galaxy/index.md
GDPR section referencing Uni Freiburg's page; table rendering on the final website was not working (however in GitHub's preview)
> GDPR statement set, table fixed - Update index.md

- content/news/2024-01-24-Madlanddb-update/index.md
Hi @shiltemann, 
Updated text as per Stefan's comments.
> Updated index.md

- src/components/Carousel.vue
Adding "ColabFold" and "New to Galaxy (23.2)" slides to Carousel.
> Add two slides to Carousel.vue

- content/events/gcc2024/training/bioconda/index.md
- content/events/gcc2024/training/frontend-dev/index.md
- content/events/gcc2024/training/index.md
Adding more training abstracts as folks complete the form
> Adding More Training Abstracts

- content/community/sig/small-scale-admins/index.md
@hrhotz tell me if it is ok for you and feel free to change.
> Small-scale galaxy admins: Add HRH and me as contact

- content/events/gcc2024/training/index.md
- content/events/gcc2024/training/vgp/index.md
Updating training index to include vgp training, and adding directory and file for VGP training
> Adding VGP Training Abstract

- content/news/2024-02-06-oscars-project-starting/index.md
> OSCARS logo visualized - Update index.md

- content/community/governance/gtb/index.md
- content/community/governance/index.md
Minor edits, partly already discussed in the recent larger review (#2302)
> Fixes on governance

- content/projects/small-scale-admins/index.md
fixes: https://github.com/galaxyproject/galaxy-hub/issues/2391
> add redirect for small-scale-admins

- content/events/gcc2024/training/index.md
In PR #1376, the fix was to add tbody tags to the table, so I'm trying that next.
> trying with explicitly declared tbody tags

- content/0examples/test-redirect-source/index.md
- content/0examples/test-redirect-target/index.md
- content/home/callouts.yml
- content/home/research.yml
- cypress/integration/main.spec.js
- cypress/support/component.js
- src/assets/styles.scss
- src/components/NavBar.vue
- src/pages/Index.vue
@afgane These innocuous changes should fix the github webhook CI errors.
> Update homepage 2 continuous integration fixes

- src/pages/Index.vue
- src/pages/usegalaxy/Redirect.vue
Also fixes any potential phishing from undesirable Url redirects.
> Fix for unsanitized URLs in the querystrings

- content/images/galaxy-logos/index.md
@GarethPrice-Aus email link fix
> Hyperlink comms@biocommons.org.au email address

- content/community/governance/gtb/index.md
Related to https://github.com/galaxyproject/galaxy-hub/pull/2415, updating GTB description based on GTB discussion on Feb 21, 2024.
> Update GTB description on page

- content/admin/get-galaxy/index.md
3.7 -> 3.8 re https://github.com/galaxyproject/galaxy/blob/dev/README.rst
> Correct the minimum python version

- content/admin/reference-mafs/index.md
Noticed a single char missing :)
> Typo fix index.md

- content/events/2024-07-22-Galaxy-Workshop-Freiburg/index.md
> Updated table

- content/bare/eu/usegalaxy/notices.md
Reverts galaxyproject/galaxy-hub#2453
> Revert "Condor switch"

- content/events/2024-04-11-data management-in-medicinal-chemistry/index.md
https://elixiruknode.org/news/2024/data-management-medicinal-chemistry/ 
GTN training 11 April 2024: 1 pm -3 pm GMT
@bgruening please feel free to update index.md
> Data management in Medicinal Chemistry

- content/gcc/index.md
@GarethPrice-Aus here's the GCC2023 logo plus attendee numbers - I couldn't preview the size, so that might need tweaking
> Add GCC2023 logo and attendee numbers

- content/news/2024-03-22-BioNT-community-event/index.md
Annocment of call for proposals for the BioNT community event.
> BioNT community event

- content/events/2024-03-22-ocean-webinar/index.md
Add fair-ease webinar on using galaxy tools to make an oceanographic analysis
> Add fair-ease webinar

- content/community/governance/geb/index.md
> Update GEB listing 

- content/events/gcc2024/training/metaproteomics/index.md
- content/events/gcc2024/training/quantum-processing/index.md
Adding another training abstract, plus minor fixes.
> Updates to training

- src/components/Carousel.vue
> Drop 23.2 release announcement from carousel

- content/events/2024-04-25-REMBI-Recommended-Metadata-for-Biological-Images/index.md
> add REMB event

- gridsome.config.js
- package.json
- yarn.lock
xref https://github.com/galaxyproject/galaxy-hub/pull/2508#issuecomment-2054194422 This may or may not pass the tests, draft.
> Plausible integrated via gridsome

- content/news/2024-04-18-DIMet-Tool/index.md
- content/news/2024-04-18-tracegroomer-tool/index.md
@bgruening 
That's exactly the provided md by Deisy Johanna Galvis Rodriguez, I just added the link to the tool on iuc
Kindly check
Thanks a lot,
Engy Nasr
> Blog post got DIMet tool Tracegroomer being added to the Galaxy EU

- content/news/2024-04-26-workflows-workflows-workflows/index.md
@bgruening was it something like that you were thinking of ?
> add fair-ease ack

- content/news/2024-05-02_Coffee/index.md
Hi @teresa-m, 
Feel free to modify the content :)
> coffee transcriptome news

- content/news/2024-04-25-psdi-webinar/index.md
News item for presentation given by @leandro-liborio as part of the EuroScienceGateway project.
> Add news item for psdi webinar on 2024-04-25

- content/ifb/lead1.md
- content/ifb/main3.md
This PR update the IFB logo and fix an URL
> Fix IFB logo and an URL

- content/events/2024-05-17-making-clinical-datasets-FAIR/index.md
add new FAIR event 'Making clinical datasets FAIR'
> add new FAIR event 'Making clinical datasets FAIR'

- content/news/2024-05-06-use-case-fabio-miloro/index.md
Added tease tag to improve tabular representation on news page
> Amendment to use case blog post by Fabio Miloro

- content/news/2024-05-14-GalaxyInResearch/index.md
Adding a Galaxy in Research post that highlights the article "Peptide Toxins from Antarctica: The Nemertean Predator and Scavenger Parborlasia corrugatus (McIntosh, 1876)".
> Add News Post

- content/news/2024-05-06-use-case-mona-malek-mohammadi/index.md
- content/news/2024-05-15-galaxy-release-24.0/index.md
Publication date (use case) and typo (release) corrected
> Corrections in news for release 24.0 and use case of Mona Malek Mohammadi

- content/citing-galaxy/index.md
Updating the "Primary Publication" citation to replace the 2022 paper with the latest 2024 paper.
> Update "Primary Publication" citation to latest paper.

- content/news/2024-05-29-checkin-usegalaxy.eu/index.md
#2568 had some issues when rendering fixing them in this PR
Images are not shown, not clear why
> Fix formatting of #2568

- content/events/2024-06-05-ARIMAgenomicsWebinar/index.md
Adding "An Introduction to Scaffolding with Hi-C Data in Galaxy" event to the events page.
> Add event to Events page

- content/events/gcc2024/training/index.md
- content/events/gcc2024/training/metaproteomics/index.md
Just a quick update to some of the language for this training and an addition of some extra trainers.
> updating metaproteomic training

- content/events/2024-06-18-fair-data-management-in-single-cell-analysis/index.md
- content/events/2024-06-18-fair-in-single-cell-analysis/index.md
add FAIR data management in single-cell analysis event
> add fair event

- .github/CODEOWNERS
- CODEOWNERS
@natwhitaker this should make it so that any time somebody opens a PR that adds a news post, you get notified (either a GitHub notification and/or email notification, depending on your own notification settings)
Maybe it helps you with content for social media.
> Add a codeowners file, notify Natalie of news posts

- content/home/research.yml
- content/use/usegalaxy-eu/index.md
- src/pages/Index.vue
> Update homepage citation nar2024

- content/events/gcc2024/training/index.md
This update adds new descriptions of the trainings and re-stylizes them so that they show the correct location and time.
> Training Schedule Update

- content/events/gcc2024/training/index.md
Cc: @afgane  @tcollins2011  @natwhitaker
> Update to Machine Learning training descriptions for GCC 2024

- content/news/2024-05-29-GalaxyTrainingAcademy-Call-Contribution/index.md
updated the teser. Here was a copy past issue. Hope it is now all corrct. 
@Delphine-L: It would be great if you can check the news post about the open call for trainers. Is everthing understandable?
> updated teaser for the call of contribution

- content/blog/2024-06-14-CoC-EoY-2023/index.md
Add 2023 CoC skeleton for editing
> 2023 CoC report draft

- content/events/gcc2024/schedule/index.md
@afgane is that all that's needed ?
> Switch workflow talks

- content/usegalaxy/index.md
Like we talked about in the Direction Summit.
> update the usegalaxy.* requirements

- content/community/sig/earth/index.md
- content/community/sig/index.md
Hello hello !
Just launched the Earth sig ! Is it okay ??
Thanks
> Add earth sig

- content/news/2024-05-29-GalaxyTrainingAcademy-Call-Contribution/index.md
extended the deadline to the 26.07
>  updated deadline

- content/careers/2020-11-hopkins-biostat/index.md
Missing closing date, made the job advert list forever
> Adding dummy closing date to a job posting

- content/community/sig/earth/index.md
- content/community/sig/index.md
Just 2 broken or wrong links that needed to be change
> Some fixes for the Earth sig page

- content/news/2024-07-08-galaxy-social/index.md
Hi, This is a blog post about [Galaxy social](https://github.com/usegalaxy-eu/galaxy-social).
Since this is my first blog post, I'm eager to hear your thoughts. Please provide feedback and let me know if any edits are needed.
> Blog post about Galaxy Social

- content/bare/eu/usegalaxy/main/index.md
> add call for trainers, remove carousel

- content/ifb/main3.md
Hello  
Links from embedded homepage to our subdomains were broken.
https://gitlab.com/ifb-elixirfr/usegalaxy-fr/welcome/-/issues/21
thank you
> allow redirection on french subdomains

- content/news/2024-07-26-shiny-phyloseq-on-EU/index.md
according to @federicomarini suggestions
> rename R-studio to RStudio in shiny-phyloseq

- content/news/2024-07-26-irccs_aoubo_hospital_bologna/index.md
I'm waiting for a "go" from the authors.
> add new post, about the Hospital in Bologna

- content/events/2024-08-07-Workshop/index.md
Updating the "Getting Started with Galaxy" workshop listed on the Events page to include a registration deadline.
> Adding Registration Deadline to Event

- content/news/2024-07-30-GalaxyInResearch_Mir/index.md
Adding "Galaxy in Research: Exploring Genetic Variability in Almond Blooming" to News.
> Adding Galaxy in Research news post

- content/news/2024-05-28-CECAM-conference/index.md
- content/news/2024-06-11-Diamond-user-group/index.md
added recent conference and poster
> Materials galaxy news

- content/news/2024-08-03-workflow-publisher-forum/index.md
... not sure which `subsites` to list as it's not Galaxy-specific.
> EuroScienceGateway news item about WorkflowHub Publisher forum

- content/use/usegalaxy-au/index.md
Minor typo in yesterday's updates
> Add missing square bracket

- content/careers/2024-08-01-CMOOR/index.md
Adding "Genomics Education Lead - Assistant Research Scientist" job posting to the Galactic Career Center on behalf of Dr. Frederick Tan.
> Add job listing to the Galactic Career Center

- content/community/sig/singlecell/index.md
> Update matrix link

- src/components/pages/SubsiteHome.vue
> Drop some twitter cruft

- content/news/2024-19-08-GalaxyInResearch/index.md
Adding a new Galaxy in Research post to News.
> Adding News post

- content/events/2024-10-07-GalaxyTrainingAcademy/index.md
Adding Galaxy Training Academy 2024 to the Events page.
> Adding Event

- content/news/2024-08-20-opinion-conda/index.md
I was asked too many times ... so I decided to write my thoughts down ...
Thanks to @fubar2 for proofreading.
> add my take to the anaconda outcry

- content/news/2024-09-03-GBCC2025/index.md
Fixing broken link in News post.
> Update News post

- src/build/run.mjs
Should address https://github.com/galaxyproject/galaxy-hub/issues/2721#issuecomment-2333778796
Let's make sure tests run to look for broken links.  And on that note, I'll follow up separately with testing the feed as well as the navigable site for broken links, so we catch all these.
> Adjust static staging path generation (again)

- content/bare/eu/usegalaxy/notices.md
We must add the Blog post/ News item URL to the notice (so it is draft)
> EU climate strike announcement

- content/news/2024-09-19-erga-ear/index.md
Added ERGA Assembly Report blogpost
> Adding ERGA EAR post

- content/bare/eu/usegalaxy/notices.md
Reverts galaxyproject/galaxy-hub#2761
> Revert "EU climate strike announcement"

- content/events/2024-11-21-hackathon-microgalaxy-iwc/index.md
Hi,
The microGalaxy organizes a hackathon to integrate, refine, and FAIRify microbial data analysis Galaxy workflows within IWC.
Bérénice
> Add event for a microGalaxy IWC hackathon

- src/components/Carousel.vue
> removing the gta card from the carousel

- content/events/2024-06-jobim/index.md
Hello, 
I'm opening this PR to add the presentations given at JOBIM 2024. This is an annual event for French-speaking bioinformatics and biostatistics. 
Thank you! 
Have a good day!
> JOBIM 2024 presentations added

- content/news/2024-10-25-GBCC2025_LogoContest/index.md
Announcing the GBCC2025 Logo Design Contest on Galaxy News.
> Create news post

- content/events/2024-10-24-egu2025/index.md
Communication to invite galaxy communities to submit abstracts to our EGU session
> Add EGU 2025 conference

- .github/workflows/optimize-images.yml
Enhance permissions for the image optimization workflow and upgrade action versions to improve functionality and security.
> Update image optimization workflow

- content/home/research.yml
Note that there was some reformatting introduced by neovim. If that's annoying, I can probably undo it.
> updating recent publications

- content/0examples/navbar.yml
- content/belgium/navbar.yml
- content/elixir-it/navbar.yml
- content/erasmusmc/navbar.yml
- content/eu/navbar.yml
- content/freiburg/navbar.yml
- content/genouest/navbar.yml
- content/home/callouts.yml
- content/home/education.yml
- content/home/research.yml
- content/ifb/navbar.yml
- content/pasteur/navbar.yml
- content/projects/esg/expected_results.yml
- content/projects/esg/external_links.yml
- content/projects/esg/objectives.yml
- content/projects/esg/partners.yml
- content/projects/esg/work_packages.yml
- content/us/navbar.yml
- package.json
Sets a standard using default prettier settings, since we don't have one now.
todo: automatically apply to PRs when necessary
xref https://github.com/galaxyproject/galaxy-hub/pull/2825#issuecomment-2489527377
> Format yml w/ prettier as well.

- content/events/gbcc2025/index.md
@afgane We can also add a toplevel galaxyproject.org nginx alias if you want once the site is live for an immediate redirect instead of the javascript one if we want it a little cleaner.
> Set up basic gbcc2025 redirect

- content/community/governance/geb/index.md
thanks for the (many) reminders @nomadscientist ;)
> Add myself to GEB

- content/events/2025-02-04-spoc_meet/index.md
- content/events/2025-03-06-spoc_meet/index.md
- content/events/2025-04-01-spoc_meet/index.md
- content/events/2025-05-06-spoc_meet/index.md
- content/events/2025-06-05-spoc_meet/index.md
- content/events/2025-07-01-spoc_meet/index.md
- content/events/2025-08-05-spoc_meet/index.md
- content/events/2025-09-04-spoc_meet/index.md
- content/events/2025-10-07-spoc_meet/index.md
- content/events/2025-11-04-spoc_meet/index.md
- content/events/2025-12-04-spoc_meet/index.md
Per the excellent advice of @hrhotz in how he co-leads the SSA community, I'm going "old-school" and making event links.
> add meeting events for 2025 SPOC community

- content/news/2024-06-11-GalaxyTrainingAcademy-Call-Contribution/index.md
- content/news/2024-12-18-SPOC_Year_in_Review/index.md
Our annual, pun-filled Year in Review
> fun SPOC news post

- content/eu/common/about-usegalaxy-eu.md
- content/ifb/main1.md
@igormakunin2 reported a typo at the landing page https://github.com/usegalaxy-eu/website/issues/1318#issue-2774332450 and I corrected two occurences [here](https://galaxyproject.org/eu/) and [here](https://galaxyproject.org/ifb/). I am not sure whether it solves the problem for [this one](https://galaxyproject.org/bare/eu/usegalaxy/main/?nonce=2883456).
> Fix "data retention police" typo

- content/events/2024-10-17-biont-python-workshop/index.md
This is the addition of the Python workshop organized by the Freiburg team last October.
> Biont Python workshop

- .github/workflows/gtn-news.yml
- utils/gtn-import-requirements.txt
- utils/gtn-import.py
Fixes https://github.com/galaxyproject/galaxy-hub/issues/2898#issuecomment-2636356875
This PR will improve the GTN news feed import and add more error handling.
Also, it will move the PR creation part into the python file for more control.
Additionally, include a requirements file to install pip packages.
> Refactor GTN news workflow and update import script for improved functionality

- content/news/2025-01-29-esg-eosc/index.md
Pending: upload video recording and update the link below.
> News item for deployment on the EOSC EU Node

- content/news/2025-01-29-esg-eosc/index.md
Updated https://github.com/galaxyproject/galaxy-hub/pull/2896/ with the correct video
> Updated video on the news "EuroScienceGateway Project: Testing the deployment of Galaxy and Pulsar on the EOSC EU Node"

- content/news/2024-10-21-eoscxnfdi-joint-symposium/index.md
I wrote a short news page for the participation of EuroScienceGateway, Galaxy, and GTN at the EOSCxNFDI 2024 joint symposium.
Maybe it is better to be reviewed by @bgruening since he was participating in this event. This news was asked for in this [issue](https://github.com/usegalaxy-eu/issues/issues/645#issuecomment-2630374273).
> EOSC x NFDI 2024 news

- content/news/2025-02-12-galaxy-release-24.2/index.md
> since the team page is terribly out of date, I'm not going to link to it

- content/bare/fr/usegalaxy/main/index.md
- content/ifb/main1.md
- content/ifb/main2.md
- content/ifb/main3.md
- content/ifb/site-footer.md
- src/pages/bare/fr/Events.vue
- src/pages/bare/fr/News.vue
- src/pages/bare/fr/latest/Events.vue
- src/pages/bare/fr/latest/News.vue
- Create a bare page for Galaxy FR
- Update info on the page
- Add more subdomains
- Make cards responsive
@abretaud could you review the changes I made? Thanks
I have only 1 issue: News and Events are empty on the bare page. I created the Vue files and modified them to try to fit to FR, but I probably missed something. @dannon What did I miss?
> Update Galaxy FR page + bare page

- utils/gtn-import.py
Using [the updated RSS feed](https://github.com/galaxyproject/training-material/pull/5799) for events to receive date, duration and external tag.
Also figured out there isn't any tag related to the events in GTN events RSS feed so that has been removed.
> Better date support for importing events from GTN RSS feed

- content/gcc/index.md
- content/news/2024-09-03-GBCC2025/index.md
> Added recent and upcoming GCC conferences

- content/news/2024-11-08-biohackathon-europe-2024-insights/index.md
Björn asked me to write a news post for Biohackathon2024. I added some salt.
> Added a news for biohackathon2024

- content/events/2025-05-12-gta2025/index.md
Event page of the GTA2025 as external event
> adding gta as external event

- content/news/2025-04-02-Fair-ease-BREST-Hackathon-2025-NewsPost/index.md
Added authors and made editions to the content of the post.
> Edited Hackathon Brest index.md blog post content

- content/news/2025-04-07-aquainfra-eosc-and-galaxy/index.md
I wrote a short news post with external link to AquaINFRA newsletter. They are going to use Galaxy as the main component of their VRE. This was asked in [this issue](https://github.com/usegalaxy-eu/issues/issues/693#issuecomment-2775817390).
> Wrote a news post based on the newsletter of AquaINFRA

- content/news/2025-04-07-galaxy-job-radar/index.md
sorry I did not realize including external url replaces the item itself...
> fix GJR news item once more

- content/events/2025-05-08-galaxy-data-snacks-series-presentation/index.md
I almost used all text from Data Snacks and provided external links. I appreciate your review.
> Added an event for the data snack presentation by Sanjay.

- content/events/2025-05-13-byow-workshop/index.md
Work Package 2 from EuroScienceGateway project is involved in this and asked us to promote the event.
> Wrote a news for Bring your own workflow workshop by ELIXIR.

- content/events/2025-05-13-byow-workshop/index.md
added logos to the esg Workflow event
> added logos to the esg Workflow event

- content/events/2025_05_19_DH_Lab/index.md
Creating an event page for a Galaxy Workshop in Freiburg
> Create event page for Galaxy Workshop on Digital Humanities in Freiburg

- content/community/sig/genome-annotation/index.md
Simple update to correct a typo in the Genome Annotation Community of Practice page
> Update index.md to correct typo in a title

- content/news/2025-05-05-Empowering-Wet-Lab-Scientists-with-NGS-Analysis-Skills-Without-Coding-Barriers/index.md
blogpost about TIaaS experience
> blogpost uwe schwartz

- content/news/2025-05-05-Empowering-Wet-Lab-Scientists-with-NGS-Analysis-Skills-Without-Coding-Barriers/index.md
I edited the news post written by Uwe Schwartz to follow Galaxy Hub formatting.
Original merged PR: https://github.com/galaxyproject/galaxy-hub/pull/3113
> Updated the news post from Uwe Schwartz about TIaaS.

- content/news/2025-05-12-tiaas-success-story-morard/index.md
The text was provided by Miguel Morard and I just added Galaxy Hub metadata section and a few hyperlinks.
> Added the news post from Miguel Morard about TIaaS.

- content/news/2025-05-15-tiaas-success-story-davila/index.md
The post text was provided by Marcela Davila and I added some formatting and metadata to the md file.
> Added a news post about positive experience of Marcela Davila.

- content/news/2025-05-18-tiaas-success-story-toivonen/index.md
The text was sent to me via email and I added the formatting and metadata related to the Galaxy Hub.
> Added positive feedback news for TIaaS written by Toivonen.

- content/news/2025-05-18-tiaas-success-story-dukowic-schulze/index.md
I received the text via email and added the formatting related to the Galaxy Hub.
> Added TIaaS success story from the TMR program by Dr. Dukowic-Schulze.

- content/news/2025-05-12-tiaas-success-story-morard/index.md
- content/news/2025-05-23-tiaas-success-story-toivonen/index.md
Two TIaaS posts were written for the same day. I changed that. Also, one author asked us to include his social media handler in his post.
> Modified the date of one post and added social media link for another one.

- content/events/2025_05_19_DH_Lab/index.md
Since they are still accepting last-minute signups
As discussed with @Sch-Da
> Remove deadline for workshop

- content/news/25-05-19-DHLab/index.md
Adding de.kcd as supporters 4 better visualisation
thanks @dadrasarmin 
hope it works now :)
> Adding de.kcd as supporters 4 better visualisation

- content/community/sig/digital-humanities/index.md
This is a first draft for a Digital Humanities special interest group in Galaxy, as suggested by @bgruening. Please add or adapt if needed.
@janleendertse I am happy for any feedback, if you have the time. 
I think I still need to 
[x] add a matrix channel here as required in the tutorial.
[x] add OR as data cleaning and MB ML as a category
[x] add imaging tools mentioned
> Add DH SIG website

- content/community/sig/index.md
Add DH SIG panel and link to index.
Is it working like this or am I missing something?
> Add DH SIG

- content/news/2025-06-w4e/index.md
This blogpost covers the recent workflow 4 experimenters in-person training which took place in Rouen, France and is organized by the MetaboHub and the Workflow4Metabolomics infrastructure.
> added w4e blogpost

- content/news/2025-06-20-GalaxyRelease25.0/index.md
Sharing a news item on the Galaxy 25.0 release.
> Galaxy 25.0 release News post

- content/news/2025-06-11-voronoi-astronomy/index.md
@dadrasarmin following up on my previous PR
> Change tags and supporters for Astro article

- content/citing-galaxy/index.md
Fixing community hub citations page
> Update Citing Galaxy index.md

- content/events/2025-09-03-ACC2025/index.md
- content/events/2025-10-14-ASHG2025/index.md
- content/events/2025-10-28-ScienceGateways/index.md
- content/events/2025-11-05-GenomeInformatics/index.md
- content/events/2026-01-09-PAG33/index.md
- content/events/2026-10-11-ASM/index.md
Adding several events to the Hub's event page.
> Adding events to Galaxy Hub

- content/events/2025-10-01-egd2025/index.md
@bgruening asked to change the agenda slightly to include more ELIXIR sections before he register the event for the ELIXIR weekly newsletter. Is the change good enough? Please let me know if I have to change more/less sections.
> Updated the agenda to highlight ELIXIR section more.

- content/events/2025-08-26-cordi/index.md
Adding event for Cordi 2025.
@teresa-m @SaimMomin12 @sanjaysrikakulam @bgruening, please add and restructure/improve as you see fit.
I followed the program's structure to name the talks, but am happy about any adjustments.
Could the 3 of you who will present please add when their talk will take place? It is in the email you got. I found the program not too clear, so I would be happy for your contribution. 
Then we can put it online. Thanks!
> Create Event for Cordi

- content/community/sig/digital-humanities/index.md
- Updating newly wrapped tools by @anuprulez, @arash77, @dadrasarmin and @RZ9082  (thanks a lot!) to the SIG Digital Humanities site. 
- adding information on upload and repository integration
> Update index.md on Digital Humanities SIG site

- content/news/2025-07-22-July2025_GalaxyNewsletter/index.md
Found minor typo in newsletter.
> Edit Newsletter

- content/events/2025-admin-training-brno/index.md
Add de.NBI to supporters list in event index
> Add de.NBI to supporters list in event index
